### ISSUE TITLE
agregar un campo nuevo en Propuesta

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#129]
En la ventana modal que falta en propuestas donde se van a capturar las condiciones de acuerdo a catalogo, agregar un campo capturable obligatorio de vigencia, este va a ser el que sale en el reporte de propuesta en el campo vigencia.

**Comment by emacevedoc** [comment]
esta debe de ser mayor o igual a la fecha d emisión .

**Comment by RoyArgaez** [comment]
¿En qué parte es esto?

**Comment by emacevedoc** [comment]
debe de abrirse una ventana modal para los datos genrerales de la propuesta..
donde vengan condiciones generales, (q salen hasta abajo) y vigencia (para capturarle una fechad de viegencia de precios., esto me gustaría discutirlo con @ircsasw  primero.

**Comment by ircsasw** [comment]
Creo que esto ya está.
