### ISSUE TITLE
Unificar monedas en cuadros comparativos

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_sps#130]
Si las partidas del cuadro comparativo están en diferentes monedas, preguntar con cuál de ellas se va a realiza la comparación de precios para definir las cantidades a colocar.

**Comment by RoyArgaez** [comment]
ESto se puede verificar.

**Comment by emacevedoc** [comment]
Los precios de la columna "Precio al TC"  deben ser unitarios... es decir    multiplicar el "precio cotizado" x el tipo de cambio de la moneda y no por el total de elemnetos a colocar.
te comento esto porque al darle actualizar veo que multiplica el numero "cantidad a colocar" x el "precio al TC"   y no esta ventana es para comparar PRECIOS UNITARIOS no totales.  me explique???

**Comment by ircsasw** [comment]
Si claro, lo cambiamos.

**Comment by ircsasw** [comment]
Ya lo verificamos y todo es a cantidades unitarias, nada se calcula con cantidad a colocar, ¿dónde viste eso?

**Comment by emacevedoc** [comment]
En la RFQ --- MPV-NOV-001 en el modulo de cuadro comparativo.
Entra y selecciona  una moneda y dale actualizar .. MXN y ves la columna de "Precio al TC" y vas a ver que se multiplica por el num asignado en "cantidad a colocar"

**Comment by ircsasw** [comment]
No, en el código no se hace nada con *cantidades*, todo es con *precios unitarios*, lo que te está pasando es que tienes mal configurado tus tipos de cambios, estas pasando de pesos a pesos pero tu tipo de cambio de peso a peso es de 2 pesos por cada peso; por eso te lo está modificando.

**Comment by emacevedoc** [comment]
tons debe validarse que no puedas guardar un tipo de cambio de una x moneda a una misma x moneda !!   eso es incorrecto verdad.. :p

**Comment by ircsasw** [comment]
Si, es mucho verdad !!!

Cierro y abro #150
