### ISSUE TITLE
Declinar y justificar Propuesta declinada

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_sps#136]
- [x] Que se pueda cambiar el estado de la Propuesta a 9. Declinada
- [x] Al declinar una propuesta se debe poder definir un mensaje con la justificación por la que se declina.

**Comment by emacevedoc** [comment]
no veo esto... solo veo el boton de inactivar..  ??

**Comment by emacevedoc** [comment]
ya vi el boton de declinar.., falta poner porque se declina la propuesta (para que el vendedor caputre la razon x la que no nos colocaron la orden.

**Comment by RoyArgaez** [comment]
Este ya se puede verificar.

**Comment by ircsasw** [comment]
No se ve el texto del motivo
