### ISSUE TITLE
Estados de Propuesta.. hacer el eviado de la propuesta al correo del contacto del cliente

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_sps#137]
Definir estados de **Propuesta** y en que momento y lugar se establecen,

1. **Creada**, cuando se Valida la RFQ y se crea la propuesta o versión de la propuesta, desde rfqs 
2. **Enviada**, cuando la propuesta se envía al cliente, desde propuestas/admin y view
9. **Declinada**, cuando se declina la propuesta (se debe justificar), desde propuestas/view

**Comment by emacevedoc** [comment]
esto no veo los estados en el modulo de propuestas !

**Comment by emacevedoc** [comment]
aquí faltan.. *enviada
que va a ser añadirle el botón de enviar por correo al menu.. y luego de que sea exitoso el envío por emial.. el estatus va a ser ese.

**Comment by emacevedoc** [comment]
HAcer de una vez lo de que se pueda enviar desde  propuestas/admin  añadir el boton en la barra de arriba "Email" y que se seleecione la propuesta a enviar y que tome el correo del contacto del cliente de dicha propuesta y lo mande a ese correo. al mandar el estado de dicha propuesta cambia a "enviada"

**Comment by emacevedoc** [comment]
@ircsasw  puedes ver que esta ya se puedan mandar por correo porfa...

**Comment by RoyArgaez** [comment]
En propuestas, cuál es el campo relacionado con el contacto del cliente?

**Comment by emacevedoc** [comment]
El email dl comprador lo ves en el detalle 

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Y el que envía el correo es el vendedor, cierto?

**Comment by emacevedoc** [comment]
Sip

Enviado desde mi iPhone

**Comment by emacevedoc** [comment]
como vas con esta @RoyArgaez

**Comment by RoyArgaez** [comment]
@emacevedoc 
Estoy por subir los cambios, le confirmo para verificar este punto.
