### ISSUE TITLE
modificaciones en los detalles de la propuesta =rfqs/armapropuesta&id al entrar a validar

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#139]
1.- no jala dato de contacto
2.- no jala dato de moneda
3.- no jala tipo de cambio
4.- no jala quien capturó
5.- no redondear cifras.. se cortan a dos decimales nada mas
6.- en el boton imprimir no se ve el reporte de la propuesta
7.- en la ultima seccion del ecabezado.. donde vienen los totales.. alinearlos a la derecha para q se entiendan.

![image](https://cloud.githubusercontent.com/assets/7875576/5221769/4cfc8a5e-7649-11e4-9a71-e12d9c0aa250.png)

**Comment by RoyArgaez** [comment]
A excepción de la **_moneda y el tipo de cambio_**, lo demás ya está, para el botón imprimir en __Viewpropuestas__ de _RFQ_ deberá crear una propuesta nueva para poder verificarla.

**Comment by emacevedoc** [comment]
no jala quien capturó la rfq
no jala el contacto quien envio la rfq
no jala notas.

**Comment by RoyArgaez** [comment]
Los campos están correctos, revisé la BD y esos campos están vacíos por eso no los muestra.
