### ISSUE TITLE
agregar el campo "fecha alta" del tipo de cambio en  tiposCambio/admin

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#146]
En el catalogo de TIPOS DE CAMBIOS en tiposCambio/admin  agregar el campo "Fecha Alta" donde "fecha alta" va a ser la fecha en la que guarde el registro, y que te permita ordenar por ese campo también.

**Comment by RoyArgaez** [comment]
Se puede verificar.

**Comment by emacevedoc** [comment]
esta se debe guardar en automatico con la fecha de guardado.. crearon el campo pero no se llena en automatico.. y no debe de ser editable...  y no debe ser nulo.

**Comment by RoyArgaez** [comment]
Se eliminó el campo *fecha_alta* del formulario de **TiposCambio/create**, se guarda automáticamente la fecha.
