### ISSUE TITLE
No se debe crear un tipo de cambio de moneda X a moneda X

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_sps#150]
Validar que cuando se cree un tipo de cambio no permita crear tipo de cambio entre las mismas monedas, Ejemplo: **PESOS A PESOS**.

Verificar en el código dónde se hacen los cálculos del tipo de cambio que se hagan correctamente cuando sea un cambio a la misma moneda.

**Comment by RoyArgaez** [comment]
Esto se puede verificar.
