### ISSUE TITLE
El propuestas/view&id componer faltan datos q no jala y modificaciones

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#152]
propuestas/view&id
en detalle de la cabecera
* no jala cliente
* no jala domicilio
* no jala telefono
* no jala RFC
* Hay dos campos de moneda !!  dejar uno y que jale el tipo de moneda
* no jala tipo de cambio
*en el detalle de las partidas, todas las columnas que sean de precios alinearlas a la derecha y solo dos decimales.

**Comment by RoyArgaez** [comment]
- [x] id_cliente
- [x] domilicio: En éste campo muestra la _calle_ como domicilio **¿Cuál debo poner?**
- [x] teléfono
- [x] Se eliminó 1 de los 2 campos de *moneda*
- [x] Se alinearon y se les quitaron dos decimales

**Comment by emacevedoc** [comment]
Domicilio completo fiscal dl cliente 

Enviado desde mi iPhone

**Comment by emacevedoc** [comment]
LA columna de la izq debe llevar
Referencia:  RFQ externo
Cliente: Nombre del cliente
RFC: RFC del cliente
Solicitado: fecha de solicitud de RFQ del cliente
Domicilio: Domicilio concatenado completo de la dirección fiscal del cliente
Comprador: quien solicito la RFQ del cliente 
email: email del comprador
Teléfono: teléfono del comprador.

En la columna del lado derecho
Cotización / Versión: Num de cotizacion / Num de versión o snapshot
Vigencia:
Moneda:
Emitido: fecha de emisión de la propuesta
Dir. Entrega: Dirección de sucursal del cliente puesta en la RFQ
Vendedor: nombre del vendedor
Email: email del vendedor
teléfono: teléfono del vendedor

favor de acomodarlo en dos columnas y no en cuatro como está actualmente para tratar de que se vea más homogéneo.

**Comment by RoyArgaez** [comment]
Esto es del **Reporte** de la propuesta o es del _propuestas/view_?

**Comment by emacevedoc** [comment]
Q no es el mismo ?? 

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Ya subí cambios, los campos de importe total, subtotal y demás cantidades, no los pongo en la cabecera?

**Comment by emacevedoc** [comment]
ok.. Solo ponle por favor las mismas etiquetas que te puse arriba estos datos.. asi como están también son los q van a ir en la cabecera del reporte impreso así como están.. 
Pero aquí en la vista de detalle le vas a agregar en las columnas lo sig.estos no van en el reporte impreso.

En la columna izq:
Notas & documentación: concatenado las notas con la documentación que va incluido
Subtotal:

En la columna derecha:
Autorizó:
TOTAL:

**Comment by RoyArgaez** [comment]
Los 3 campos nuevos van en la parte de la cabecera o en la parte de abajo?
