### ISSUE TITLE
Correciones en el reporte de la propuesta

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#153]
favor de dejar un poquito mas prolijo el reporte.
- [x] dividir la cabecera en dos secciones del mismo tamaño.
- [x] referencia y cotización los dos primeros campos de ambos lados todo con negritas, tanto etiqueta h  como valor
- [x] de un lado la sección de datos de cliente y la otra la sección de MARINE
- [x] de los datos q aparecen hay unos q hay que cambiar d lugar puesto q estan cruzados.

ejemlo:
- [x] vendedor  vs comprador.. van invertidos.
- [x] vendedor va del lado derecho y comprador lado izq.
- [x] el emial que ya jalas ahi es del comprador va del lado iz.. del otro lado (derecho poner email del vendedor)
- [x] ambos campos alienados al mismo nivel.
eso en es las cabeceras..

en el detalle de las partidas. 
- [x] item mas pequeño de ancho!!
- [x] descripcion el titulo va centrado pero el detalle alineado a la izq, 
- [x] cantidad... ponlo abreviado Cant.
- [x] p/u e importe el titulo centrado, pero el detalle alineados a la derecha y con dos decimales nada mas.

- [x] abajo  volver a poner el campo Moneda: en donde va subtotal y total (la abreviación)  USD, MXN, CAN,
- [x] agregar abajo de documentación, Lugar de entrega.

**Comment by RoyArgaez** [comment]
¿Del lado derecho van los datos del Cliente y del lado izquierdo la información de Marine?

**Comment by emacevedoc** [comment]
Derecho marine, izq cliente 

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Quedaría así:

 CLIENTE |   MARINE
------------ | ------------ 
    Cliente  |  Fecha de emisión
    Domicilio  |  Vigencia
    Teléfono  |  Revisión
    RFC  |  Tiempo de entrega
    Fecha de solicitud  |  Moneda
    Comprador  |  Vendedor
    Email  |  Autoriza
    Celular  |

¿Está bien el orden de la cabecera? o ¿falta algún campo?

**Comment by emacevedoc** [comment]
Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
¿...? 

No me llegó su mensaje. solo se muestra (enviado desde mi iPhone)

**Comment by emacevedoc** [comment]
Es q me mando error !! Y tengo q volver a hacerlo pero este mejor t lo hago en mi pc aquí me cuesta trabajo .

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Okey, acabo de subir los últimos cambios en el reporte, puede verificarlos y notificarme si necesita más cambios.

**Comment by emacevedoc** [comment]
ok... mañana con calma veo este ... :)  lo voy a abrir... xq no me dio chance de volverte a escreibir los del telefono..

**Comment by RoyArgaez** [comment]
Hice las últimas modificaciones tanto al reporte de propuestas como a la cabecera de la vista, puede verificarlo.

**Comment by emacevedoc** [comment]
cotizacion / version...   en el view...     debe de ir  #de cotizacion / #de version.
únicamente viene el numero de cotizacion... tiene q ir con su numero de version separada con la diagonal

el campo de iva en la version impresa debe de ir alineado, con subtotal y total, fíjate que sale descuadrado.

el campo vendedor en la version impresa esta mal, esta mostrando el comprador del cliente..

el campo en letra de la propuesta impresa... los decimales.. tienen   0000/100 ...  deben ser solo dos ceros sobre 100 en el caso d que sea 0 centavos.

**Comment by RoyArgaez** [comment]
Ya subí los cambios, en la parte del _subtotal_, _iva_ y _total_ el campo de _moneda_ está en una celda separada que el de la cantidad.
En la web está de una forma diferente a la imagen, puede revisar los cambios subidos y si están bien los cambios o los modificamos.

![captura de pantalla de 2015-02-04 11 13 59](https://cloud.githubusercontent.com/assets/4944467/6043004/f48c8608-ac4e-11e4-9efc-5c2bbaa2116d.png)

**Comment by LUISGER** [comment]
Roy,

hice un ejercicio y no sale la moneda:

![image](https://cloud.githubusercontent.com/assets/10568343/6043525/613514e8-ac52-11e4-948e-c0d358ce6f39.png)

**Comment by ircsasw** [comment]
@LUISGER puedes usar la arroba "@" para hacer referencia a un usuario.

Si un issue está cerrado y crees que no debe estar cerrado o aun no queda resuelto, puedes comentar como ahora pero recuerda "re-abrir" el issue para que lo podamos ver en la lista de pendientes.

**Comment by emacevedoc** [comment]
si estan bien... solo falta poner bien en  la cabecera... las dos primeras columnas del view.. ya que aún estan incorrectas las del reporte.

**Comment by emacevedoc** [comment]
* El nombre de vendedor sale en minúsculas, favor de poner en mayúsculas
* dice DIMICILIO debe DOMICILIO 
* donde dice tel vendedor,  sólo debe decir TELÉFONO
* donde dice tel comprador,  sólo debe decir TELÉFONO
* donde dice email vendedor, sólo debe decir EMAIL
* donde dice email comprador, sólo debe decir EMAIL
* donde dice fecha de solicitud, debe decir SOLICITUD
* donde dice fecha de emisión, debe decir EMISION
* documentación lleva acento , hasta abajo
Esto con la finalidad de que las columnas se ajusten mejor y se vea más prolijo. 

Un detalle importante es que estas columnas no se han puesto como el del view que te mencione deben ser igual a a las dos primeras, si te fijas están mal .. Del lado izq por ejemplo aparece dos veces el domicilio del cliente ¡,

**Comment by RoyArgaez** [comment]
Dónde aparece dos veces? un campo es el de _Domicilio_ y el otro es el de _Lugar de entrega_, lo puede verificar.

**Comment by emacevedoc** [comment]
Faltó la de poner el nombre del vendedor en mayúsculas...
Y domicilio del lado de la columna de datos del cliente aparece
En 3 ero y 6to lugar ..

**Comment by RoyArgaez** [comment]
El nombre del vendedor aparece en mayúsculas por que así está guardado en la BD, pero lo modifico.
Y ya eliminé la columna duplicada, mi error.

**Comment by emacevedoc** [comment]
#Cotizacion / #Version :  del lado derecho el primer campo debe verse como el view... y se elimina el segundo campo.

**Comment by RoyArgaez** [comment]
Lo puede verificar.
