### ISSUE TITLE
Columnas para propuestas/ventaporcliente

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_sps#156]
Item | Descripción | Desc Cotizada | Cantidad | Unidad | Precio Unit | Importe Total | Tiempo Entrega
------ | ----- | ----- | ----- | ----- | ----- | ----- | -----

Nota: En esta vista y en las otras que resultan de propuestas\ventaspor.

**Comment by emacevedoc** [comment]
cantidad, precio unitario, importe total deben alinearse a la derecha para que sea legible.
precios y cantidades deben alinearse siempre a la derecha en todas las tablas.

**Comment by RoyArgaez** [comment]
Puede verificarlo.
