### ISSUE TITLE
No lleva paginación en propuestas/ventasporcliente

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_sps#157]
Este grid y el de todos los que vienen de propuestas/ventaspor no llevan paginación, el grid debe mostrar TODOS los datos encontrados.

**Comment by emacevedoc** [comment]
aun se no se ven !  propuestas/ventaporclie   sigue viéndose con paginación

**Comment by RoyArgaez** [comment]
Ya lo puede verificar.

**Comment by emacevedoc** [comment]
propuestas/ventaporclie&id=50   sigue viendose con paginación

**Comment by RoyArgaez** [comment]
Esto se puede verificar
