### ISSUE TITLE
ordenar alfabeticamente

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#160]
cuando das de alta un proveedor nuevo, y te vas hasta abajo a seleccionar que familias le vas a asignar..
 * ordenar la lista de familias del droplist alfabéticamente en catalogo de proveedor. _proveedores/create_
* ordenar el catalogo de familias también.. que el grid salga ordenadas por familia _familias/admin_

**Comment by RoyArgaez** [comment]
Esto se puede verificar.
