### ISSUE TITLE
corregir cantidad con letra en propuesta impresa

### ISSUE THREAD

**Issue by LUISGER** [lauraeg/incidencias_sps#161]
en la cantidad cpon letra, la coma debe ser mil (es) 

![image](https://cloud.githubusercontent.com/assets/10568343/5941992/4860eca8-a6da-11e4-82fd-24601e7caf1b.png)

**Comment by ircsasw** [comment]
@RoyArgaez la función para pasar la cantidad a letras no está recibiendo un número, está recibiendo la cadena "1" "," "6" "2" "8" "." "5" "0", para este caso, por eso sale de esa manera. Hay que mandar a la función el número: 1628.50, para este caso.

**Comment by RoyArgaez** [comment]
Esto se puede verificar.

**Comment by emacevedoc** [comment]
no sale bien ni la cantidad en letras, ni en numeros ahora..
![image](https://cloud.githubusercontent.com/assets/7875576/6048371/64853420-ac75-11e4-8503-4f699dedeb19.png)

**Comment by RoyArgaez** [comment]
Estoy revisando las propuestas y veo que las primeras que no tienen el id del cliente no tienen ni precio, si imprime otra más adelante sale sin problemas.
