### ISSUE TITLE
homogenizar los catalagos

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#162]
oye.. hay catalogos q guardan todo con mayuscula y hay que guardan todo con mayusculas y minusculas.. eso hace que a la hora de imprimir el reporte salsa tutifruti.

podemos hacer que todo sea mayusculas y minusculas.. ??
y solo RFC en mayusculas ??   porfa....

ejemplo...
el catalogo de contactos de clientes todo es con mayusculas...
el catalogo de usuarios en con minusculas..
en el reporte de la propuesta... se ve chile y manteca la cabecera... pero ya vi que el error esta desde la captura.

**Comment by ircsasw** [comment]
@RoyArgaez hay una función en los campos de texto de los catálogos que pasa todo a mayúsculas.

**Comment by RoyArgaez** [comment]
Esto ya se puede verificar

**Comment by emacevedoc** [comment]
el catalogo de usuarios sigue con minusculas el nombre..   es importnate ya que sale en el reporte final

**Comment by ircsasw** [comment]
@RoyArgaez verifica en todos los catálogos

**Comment by RoyArgaez** [comment]
He revisado todos los archivos, puede verificarlo nuevamente.

**Comment by emacevedoc** [comment]
el catalogo de usuarios sigue estando minusculas el nombre ....

**Comment by ircsasw** [comment]
> podemos hacer que todo sea mayusculas y minusculas.. ??
> y solo RFC en mayusculas ?? porfa....

@emacevedoc tu pediste que todo sea mayúsculas y minúsculas y que sólo los RFC sean en mayúsculas.

**Comment by emacevedoc** [comment]
ok....  hagamos la mejora en el reporte :) y ya no tocamos los catalogos...
