### ISSUE TITLE
Bandera para más información de RFQ

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_sps#163]
@emacevedoc puedes revisar el proceso para solicitar más información de una RFQ.

Puedes ver el botón en *rfqs/admin* 

Debes marcar la RFQ que necesita más información y esta queda marcada con la bandera y regresa su estado a 1. No atendida.

![image](https://cloud.githubusercontent.com/assets/919978/5970125/a2887600-a7f3-11e4-82c2-016c2c25d053.png)

**Comment by ircsasw** [comment]
@RoyArgaez falta:

- [ ] Identificar en el grid de *rfqs/admin* las RFQ marcadas con la bandera de **Más Información**
- [ ] Desmarcar desde el grid. **ANALIZAR!!**

**Comment by ircsasw** [comment]
@RoyArgaez 

- [ ] Un flotante dónde se indique que información es la que falta.

**Comment by emacevedoc** [comment]
esta la voy a cerrar puesto q ya cambio con el otro isseu q abriste.
