### ISSUE TITLE
estatus de RFQ erroneo

### ISSUE THREAD

**Issue by LUISGER** [lauraeg/incidencias_sps#164]
Marina,

aqui puedes ver como aparece declinadas todas las partidas y aparece un estatus de atendida parcial:

![image](https://cloud.githubusercontent.com/assets/10568343/5984450/f1a89ad2-a89b-11e4-8458-f4901d912368.png)

![image](https://cloud.githubusercontent.com/assets/10568343/5984462/0bad28ee-a89c-11e4-986c-6a89f5e93847.png)

**Comment by emacevedoc** [comment]
esta ya no la veo.. si ya la desactivaste no lo puedo revisar...
