### ISSUE TITLE
poner obscuras los campos no editables

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#165]
en solicitudes/update los campos "fecha" y "fecha de captura" de la cabecera y en el grid de abajo
"Unidad Solicitada"   y 	"Acepta Sustituto"  ; favor de poner en gris ya que no son editables y se presta a confusión.

es posible que el focus se ponga de inicio en fecha vigencia???

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
"Unidad Solicitada" y "Acepta Sustituto"  siguen viéndose en claro..

**Comment by ircsasw** [comment]
> en solicitudes/update los campos "fecha" y "fecha de captura" de la cabecera y en el grid de abajo
> "Unidad Solicitada" y "Acepta Sustituto" ; favor de poner en gris ya que no son editables y se presta a confusión.

@RoyArgaez verifica bien antes de cerrar.

**Comment by RoyArgaez** [comment]
No entiendo lo que me está pidiendo, estoy revisando el grid y lo veo Gris, qué es lo que está pidiendo?

**Comment by emacevedoc** [comment]
los campos "Unidad Solicitada" y "Acepta Sustituto" en el grid donde estan las partidas de la solicitud, ![image](https://cloud.githubusercontent.com/assets/7875576/6048313/eee1a9f6-ac74-11e4-9f9a-c45d2512ae30.png), son campos q estan bloqueados para su edición, pero requiero q se pongan en gris como los primeros.

**Comment by RoyArgaez** [comment]
Pues yo lo estoy viendo desde la WEB, y me aparecen en GRIS como usted lo pide.

![captura de pantalla de 2015-02-04 17 29 12](https://cloud.githubusercontent.com/assets/4944467/6050169/81f25392-ac8b-11e4-99b4-4229e00cd20e.png)

**Comment by ircsasw** [comment]
@emacevedoc en tu pantalla esos items aceptan sustituto por eso esos campos están activos, @RoyArgaez en tu pantalla esos items NO aceptan sustituto por eso esos campos están inactivos.

**Comment by emacevedoc** [comment]
ok. aunque acepten o no sustitutos son campos solicitados x el cliente d esa manera.. esos no pueden ser editables al momento d capturar lo propuesto..
el unico que cambia a no editable dependiendo de lo que pidio el cliente el Cotiza sustituto.

pero yo estoy hablando de "unidad solicitada" y "acepta sustituto" deben ir siempre en gris y bloqueados.

**Comment by ircsasw** [comment]
@emacevedoc lo sé, a lo que me refiero es que el problema está en la configuración de la vista para los que NO aceptan sustitutos, @RoyArgaez eso es lo que debes revisar.

**Comment by RoyArgaez** [comment]
Le agregué a  _"unidad solicitada"_  y _"acepta sustituto"_ un background para que se distinga el color.
