### ISSUE TITLE
mismo error de estatus en RFQ

### ISSUE THREAD

**Issue by LUISGER** [lauraeg/incidencias_sps#167]
hay que revisar el criterio de adjudicacion de estatus, aparce esta otra con el mismo error:

![image](https://cloud.githubusercontent.com/assets/10568343/6040742/0190948e-ac3b-11e4-8886-f3812b853120.png)

**Comment by emacevedoc** [comment]
@LUISGER no abras x abrir... !!  son indivuduales cada issues, esta por si sola no me dice nada ni de que error estas hablando ! solo tu lo entiendes...

**Comment by emacevedoc** [comment]
a ver.. @ircsasw   esta solo tiene una partida... pero esa partida internamente esta como no atendida... pero la RFQ aparece como atendida parcial.   si fue en algun cambio que hicimos solo dime.. pero no debiera estar en ese estado la rfq si su unica partida esta como no atendida aún.

**Comment by ircsasw** [comment]
Una RFQ sólo puede estar "Atendida parcial" cuando al menos uno de sus items están "Solicitado", un item puede estar "Solicitado" cuando está incluido en al menos una Solicitud.

El item no está en ninguna Solicitud, su estado es correcto, "No atendido".

Viendo en la base de datos la auditoria de esos registros, no se han modificado desde que se crearon, tanto el registro de la Rfq como el Item.

Ya hemos revisado el proceso de los estados varias veces, en todas nuestras pruebas el ciclo se realiza correctamente, pero, lo revisamos de nuevo, mientras le pongo desde la base de datos su estado correcto.
