### ISSUE TITLE
no coindicen los datos de la vista con lo del reporte.. ni con los calculos.

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#168]
no se donde estuvo el error en esta.. pero mira esto..
![image](https://cloud.githubusercontent.com/assets/7875576/6064125/8f10db48-ad21-11e4-9f85-8011c49593c7.png)
 
![image](https://cloud.githubusercontent.com/assets/7875576/6064140/9fffb776-ad21-11e4-876a-f36b14f5adfc.png)

desde mi punto de vista.. los calculos d  iva y subtotales deben ser calculados en el reporte.. pero veo que son jalados de la base de datos tambien... pero no estan correctos ni en la vista los calculos.. ni en el reporte..

**Comment by ircsasw** [comment]
@emacevedoc esos valores se calculan, nunca se guardan, revisamos.

**Comment by RoyArgaez** [comment]
Los cálculos se calculan bien, esa propuesta se generó así como aparece en la imagen. Puede verificar otras.

**Comment by emacevedoc** [comment]
El error está en el grid. Mira ya revise otras y esta igual .. El precio unitario x la cantidad me debe dar la columna importe y no la esta calculando correctamente en la imagen de arriba. Te da 2x 2 =4'875.   Algo esta mal ahi ..  Igual en la propuesta 22 fíjate en las partidas su partida 4 dice  5 x 1. =9,213.75.  !!!!
