### ISSUE TITLE
rfq 10056943 se capturaron $, esta cotizada y en cuadros dice q no existe

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#169]
![image](https://cloud.githubusercontent.com/assets/7875576/6065027/ae8d6bfc-ad27-11e4-9665-c16c5e1bc6d0.png)
![image](https://cloud.githubusercontent.com/assets/7875576/6065045/cf97f092-ad27-11e4-9cd4-0b18e0336937.png)

**Comment by ircsasw** [comment]
Si la busco directo en la base de datos por rfq externo, no me regresa nada:
![image](https://cloud.githubusercontent.com/assets/919978/6065941/0bac5474-ad37-11e4-95b8-d1c06b717835.png)

Si la busco por id, me regresa la rfq, y se puede ver que el rfq externo está mal capturado, tiene un espacio al principio:
![image](https://cloud.githubusercontent.com/assets/919978/6065981/64d36a38-ad37-11e4-8be8-aa66e7721de8.png)

La tienes que editar.

**Comment by LUISGER** [comment]
al hacer la propuesta, y darle imprimir sale en blanco!!

![image](https://cloud.githubusercontent.com/assets/10568343/6073476/7b469816-ad74-11e4-8c98-f061e376379f.png)

**Comment by LUISGER** [comment]
Al validar la propuesta: 
![image](https://cloud.githubusercontent.com/assets/10568343/6073876/3b11ea1a-ad7a-11e4-8e88-18c535a4532f.png)

me sale esto:
![image](https://cloud.githubusercontent.com/assets/10568343/6073881/49f98a4c-ad7a-11e4-88e0-76dbd2c6f097.png)

**Comment by RoyArgaez** [comment]
Esto lo puede verificar.
