### ISSUE TITLE
Si no hay partidas con precio, no debe permitir hacer propuesta ni validar

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#171]
Porque resulta en esto una propuesta vacía ,
![image](https://cloud.githubusercontent.com/assets/7875576/6080938/1249d0a0-addb-11e4-8c6c-a3f80af8f8e9.png)

Debe haber una validación al momento de enviar a validar creo yo..  no hay nada que validar si no hay partidas con precio.. ya sea que se inactive el boton de enviar a validar (así no se generan snapshot vaciós y basura)
![image](https://cloud.githubusercontent.com/assets/7875576/6080982/74c5f43e-addb-11e4-86c5-9dd3e47a3a6a.png)

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
cambiar el mensaje debe salir.- "No tiene partidas asignadas aún. no puede hacer una propuesta"

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by ircsasw** [comment]
Es más claro:
*No puede hacer una propuesta. Aún no tiene partidas asignadas."

@emacevedoc ?
