### ISSUE TITLE
error en calculos  en la propuesta

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#172]
No se porque hace mal los calculos ???    si te fijas en lo que marque de azul... la multiplicación no debe dar 1  !!   en esa misma propuesta mas abajo hay otro que tambien tiene 1, checalas porfa.
![image](https://cloud.githubusercontent.com/assets/7875576/6081113/a3096abe-addc-11e4-9940-1e608ac514c9.png)

**Comment by RoyArgaez** [comment]
Lo acabo de probar y me muestra las cantidades correctas. estoy en la web. puede verificarlo de nuevo?

**Comment by emacevedoc** [comment]
Ahorita ya se ve .. Pero prueba d que estaba mal ahi ta la imagen Jijiiji
