### ISSUE TITLE
La cabecera del reporte debe repetirse en todas las hojas de la propuesta

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#173]
Los datos de Marine.. completos hasta la primera linea azul.. son los que deben aparecer en cada hoja![image](https://cloud.githubusercontent.com/assets/7875576/6081242/bddb3ace-addd-11e4-97c1-08d56b6681ee.png)

y abajo de la linea inferior donde va la paginación.. dede de ir..

_____________________________________________________________________
Cotizacion:  #cot  /  #Version         ---------               Paginas  1 / n

**Comment by ircsasw** [comment]
@RoyArgaez en la documentación de TCPdf está cómo definir encabezados y pies de página para los reportes, estos datos deben estar como encabezado.

![image](https://cloud.githubusercontent.com/assets/919978/6111828/a5198b34-b059-11e4-962f-f082bdbb0c8a.png)

**Comment by emacevedoc** [comment]
Y en el pie .. El nun d cotizacion , la versión y lo d las pag 1 / n

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
- [x] Cabecera repetida en todas las hojas
- [ ] Pie de página
