### ISSUE TITLE
??? x hay dos folios con clientes distintos ?? se supone q el folio es único no???

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#176]
entiendo q de un folio pueden haber varias versiones.. pero no deben haber folios de clientes distintos..no se como paso... pero no esta de mas checarlo.
![image](https://cloud.githubusercontent.com/assets/7875576/6100545/4066096a-afd7-11e4-9f13-257b07feb0bd.png)

**Comment by lauraeg** [comment]
@RoyArgaez , Revisa por favor

**Comment by ircsasw** [comment]
@RoyArgaez de hecho hay varios 21 con revisión 0

**Comment by emacevedoc** [comment]
Si el folio puede ser el mismo pero debe ir camviando la versio. D una propuesta d un mismo cliente pero si es una propuesta nueva a otro cliente debe ser otro folio 

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
¿Por qué las anteriores con _folio_ 21 y _revisión_ 0 no tienen items propuestos?

**Comment by RoyArgaez** [comment]
Estuve haciendo prueba y las dos útimas las acabo de crear y sin problemas.

![captura de pantalla de 2015-02-09 19 41 34](https://cloud.githubusercontent.com/assets/4944467/6119305/045d9de8-b095-11e4-8906-7b7c3ec741e2.png)

**Comment by emacevedoc** [comment]
Ok .. Probablemente  era antes d los folios.. Voy a cerrarlo si detecto de nuevo la falla lo abro
