### ISSUE TITLE
agregar dos columnas en el grid _propuestas/ventaporclie_

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#178]
la primera columa antes del item.. debe ser RFQ externa y
despues de precio unitario, agregar el campo moneda

**Comment by RoyArgaez** [comment]
- [x] Campo moneda en vistas: ventaporclie, ventaporfolio, ventaporrfq
- [x] campo precio_unitario en vistas: ventaporclie, ventaporfolio, ventaporrfq
- [x] campo rfq_externo solo en vista ventaporrfq

**Comment by emacevedoc** [comment]
no veo el rfq externo.. en _propuestas/ventaporclie&id_  debe de ir como primer columna

**Comment by emacevedoc** [comment]
1-El rfq externo debe funcionar como los otros campos , ordenando y filtrando
2. El campo moneda aparece dos veces

**Comment by RoyArgaez** [comment]
- [x] se eliminó un campo moneda

**Comment by emacevedoc** [comment]
No funciona así en propuestas/ventaporrfq&id=1056&rfqexterno

**Comment by RoyArgaez** [comment]
Puede verificarlo, lo omití en el de ventaporrfq ya que en esa vista aparecen todas las de un solo RFQ.

**Comment by emacevedoc** [comment]
todas las vistas. deben verse en el grid como se ve la de propuestas/ventaporclie... las mismas columnas.

**Comment by RoyArgaez** [comment]
Se puede verificar.

**Comment by emacevedoc** [comment]
En propuestas/ventaporrfq&id=1047&rfqexterno=23709 se ve dos veces la columna moneda.. Se debe eliminar la primera

**Comment by RoyArgaez** [comment]
Listo
