### ISSUE TITLE
luego de seleccionar cuales items me colocaron, agregar el boton de continuar

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#179]
y al darle continuar... que se abra una grid parecido al de cuadros comparativos, para que puedan modificar las cantidades que me coloco al final el cliente. y posterior a esto, poner los datos generales de la orden de compra del cliente,

**Comment by RoyArgaez** [comment]
¿En qué ventana selecciona los items?

**Comment by emacevedoc** [comment]
Propuestas/ventaporclie

**Comment by RoyArgaez** [comment]
@emacevedoc : ¿Qué datos va a llevar esta parte?

**Comment by emacevedoc** [comment]
sip... estan en el drive... y en la #213
