### ISSUE TITLE
agregar un boton en rfqs/armapropuesta "condiciones"

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#180]
en la barra superior, junto al botón de validar agregar un botón que se llame condiciones.
y abrirá una ventana donde seleccionaré las condiciones del catalogo Condiciones que formaran parte de la propuesta.
el issue #189 tiene que hacerse primero y luego este.

**Comment by ircsasw** [comment]
El proceso:
- [ ] Agregar el campo *rfqs.condiciones_propuesta* (ver drive)
- [ ] En *rfqs/armapropuesta* poner un botón que muestre un modal para llenar el campo
- [ ] El campo se llena seleccionado condiciones que se agregan una después de la otra
- [ ] Estas condiciones van a la propuesta

**Comment by RoyArgaez** [comment]
@emacevedoc se agregará un campo nuevo llamado condiciones a *Propuestas* o se utilizará uno que ya está en la BD?

**Comment by emacevedoc** [comment]
el campo ya esta... pero aun no hay donde capturarlo al editar la propuesta...
no lo veo.. el botón debe de aparecer en _rfqs/armapropuesta_  y cuando le den clic al boton debe aparecer una ventana modal donde seleeciones las condiciones (del catalago de condiciones)  pueden ser mas de una.. y las que seleeciones... apareceran en el campo condiciones de la propuesta.
@ircsasw  esta bien así ??

**Comment by RoyArgaez** [comment]
En la vista _rfqs/armapropuesta_ está el botón de **condiciones**. Es correcto el proceso que usted menciona, eso puede verificarlo.

**Comment by emacevedoc** [comment]
No veo el botón

**Comment by RoyArgaez** [comment]
El botón aparece cuando la requisición tiene estado 4. _En validación_

**Comment by emacevedoc** [comment]
No en validación ya tiene todas las condiciones puesta ya q validación solo es una revisión de la propuesta. Completa antes de formalizarla al cliente

Enviado desde mi iPad

**Comment by RoyArgaez** [comment]
Puede verificarlo.
