### ISSUE TITLE
agregar boton de "regresar"

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#182]
en la pantalla _propuestas/view_ agregar en la barra superior el mismo botón de "regresar" como está en _rfqs/armapropuesta_ y que funcione de igual manera.

**Comment by ircsasw** [comment]
![image](https://cloud.githubusercontent.com/assets/919978/6111560/cf74159a-b057-11e4-80fa-46769fb629d1.png)

@RoyArgaez el botón Rojo

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
Pregunta q diferencia hay entre el botón de regresar en rojo del botón de regresar en amarillo q está en http://sps.marineprov.com/index.php?r=propuestas/reppropuesta&id=22.   ......¿..¿¿.¿.

**Comment by RoyArgaez** [comment]
En realidad sólo el color tiene diferente :P ya le puse el amarillo.

**Comment by emacevedoc** [comment]
ok.. pero el estado de las propuesta siguio quedando en PROPUESTA....

**Comment by RoyArgaez** [comment]
La propuesta no puede cambiar de estado a uno anterior ya que solo tiene un estado **1.Propuesta** al igual que sus items, se puede declinar o desactivar, pero no puede regresar un estado anterior.
