### ISSUE TITLE
cambiar nombre de "TIEMPO DE ENTREGA" a      "T.E.*"

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#184]
en la columna  de Tiempo de entrega cambiarle el nombre,  y reducirla de ancho.
abajo luego de las notas inferiores.. abajo de lugar de entrega
poner la leyenda en letra pequeña  :  * Tiempo de Entrega en Dias

**Comment by lauraeg** [comment]
> en la columna de Tiempo de entrega cambiarle el nombre, y reducirla de ancho.
> abajo luego de las notas inferiores.. abajo de lugar de entrega
> poner la leyenda en letra pequeña : * Tiempo de Entrega en Dias

@emacevedoc . En dónde necesitas eso?

**Comment by emacevedoc** [comment]
En el reporte d propuesta impreso

**Comment by RoyArgaez** [comment]
Lo de **tiempo de entrega en días** va abajo de _lugar de entrega_ o dentro del campo de _tiempo de entrega_

**Comment by emacevedoc** [comment]
Abajo

**Comment by RoyArgaez** [comment]
Lo puede verificar

**Comment by emacevedoc** [comment]
falto el asterisco en la columna  ..  
debe decir:       T.E.*   
y la leyenda abajo solo lleva el asterisco inicial.. no lleva el final

**Comment by RoyArgaez** [comment]
se puede verificar

**Comment by emacevedoc** [comment]
Oye olvide ponerle          días hábiles.  Sólo puse días .. Perdon
