### ISSUE TITLE
Nuevos campos y cálculos en solicitudes/update

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_sps#186]
Agregar nuevos campos a partidas de la solicitud:
- [x] Descuento (descuento_cotizado)
- [x] IVA (tasa_iva_cotizada)
- [x] IEPS (tasa_ieps_cotizada)

- [x] Realizar los cálculos correspondientes. Tomar en cuenta el tipo de cambio.

- [x] El orden de los campos

... | Cantidad Cot | Unidad Cot | UnidXEmp | Precio Cot | Descuento | IVA | IEPS | Moneda Cot | ...
--------- | ---------- | --------- | ---------- | --------- | ---------- | --------- | ---------- | --------- | ----------

**Comment by RoyArgaez** [comment]
Se puede verificar

**Comment by emacevedoc** [comment]
iva por default..  16

**Comment by RoyArgaez** [comment]
Se puede verificar.
