### ISSUE TITLE
_solicitudes/admin_ agregar boton en la barra de arriba de "Declinar"

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#187]
que al apretar este botón,,   todas las partidas de la solicitud de cotización se pongan en Declinada su estado.. y el estado de la solicutd de cotización , tambien cambie a Declinado.

al igual como esta en la pantalla _propuestas/admin_ ...     tambien debe preguntar porque declinas y abrir el cuadro para capturar la razon del decline.

**Comment by ircsasw** [comment]
@RoyArgaez, proceso para declinar partidas; si todas las partidas de una solicitud están declinadas, de declina la solicitud.

**Comment by RoyArgaez** [comment]
Esto lo puede verificar.

**Comment by emacevedoc** [comment]
me sale este error.. 
![image](https://cloud.githubusercontent.com/assets/7875576/6546946/f788df4e-c58c-11e4-8d8f-189b623fc094.png)

**Comment by RoyArgaez** [comment]
@emacevedoc  El error que usted me muestra es de **RFQS** lo verifico.

**Comment by RoyArgaez** [comment]
Esto lo puede verificar por favor.

**Comment by emacevedoc** [comment]
ya verifique en las solicitudes de cotización...  esas ya quedaron...

 solo que al declinarla se debe de guardar la fecha de declinación en la fecha de respuesta también.

y me quedo la dura de los del RFQS ????? como llegue a ese error jajaja

**Comment by RoyArgaez** [comment]
Okey, verifico lo de la fecha de declinación.

**Comment by RoyArgaez** [comment]
Esto ya lo puede verificar.

**Comment by emacevedoc** [comment]
cambiale el nombre ya que en el titulo de la ventana dicen  requisiciones inactivas.. y no son requisiciones son solicitudes de cotizacion.. !

**Comment by RoyArgaez** [comment]
lo puede verificar
