### ISSUE TITLE
en_rfqs/armapropuesta_ no funciona el boton d imprimir.. 

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#188]
debe verse la propuesta.. como va quedando.. 
no debe salir con numero de propuesta
no debe salir vigencia
no debe salir autoriza
ni fecha de propuesta.. puesto que aun no la validan.. pero debe porderse ir viendo los demás campos-- si quieres sería bueno que saliera alguna marca de agua.. que dijera.. DRAFTH   o BORRADOR

**Comment by ircsasw** [comment]
@emacevedoc 

¡¡¡¡como va quedando la propuesta!!!!!

No, ese botón te hace la vista de la propuesta de esa RFQ, la última, ya sea folio o revisión.

Eso que quieres ver, es lo que se ve en la ventana sin darle imprimir, no??

Ese botón es un acceso al reporte de la propuesta desde la RFQ, para que no tengas que ir a la propuesta si no sabes cual es, vas a la RFQ y generas su reporte de propuesta (el último) de esa RFQ desde la RFQ.

Nota: @emacevedoc  lo cierro para que lo comentes.

**Comment by emacevedoc** [comment]
no t entendi.. mañana lo revisamos x teléfono¡ @ircsasw
