### ISSUE TITLE
agregar un campo al catalogo de condiciones llamado Categoria

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#189]
es a la categoria que pertenece dicha condición.

_condiciones/create_
el campo nuevo llamado Categoría..  son de 3 tipos puede ser un list.
* Pago
* Entrega
* Otros

y en el grid _condiciones/admin  agregar la columna también.

ahora bien.. las condiciones están en el issue   #180

**Comment by ircsasw** [comment]
@RoyArgaez el campo está definido en el drive, *condiciones.categoria*

**Comment by RoyArgaez** [comment]
Este se puede verificar.

**Comment by emacevedoc** [comment]
@ircsasw FAVOR DE AGREGAR A LA LISTA DE CATEGORIAS  * CANCELACIONES

**Comment by RoyArgaez** [comment]
Se puede verificar.
