### ISSUE TITLE
Totales de rfqs/armapropuesta con el tipo de cambio

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_sps#190]
@RoyArgaez 
En la vista rfqs/armapropuesta se hace el cierre de los importes (RfqsController línea 415), este cierre debe tomar en cuenta el tipo de cambio de cada moneda de las partidas a Pesos.

![image](https://cloud.githubusercontent.com/assets/919978/6141042/fe768532-b16d-11e4-990c-339530704fa2.png)

**Comment by RoyArgaez** [comment]
Esto se puede verificar.
