### ISSUE TITLE
filtrar las rfqs que ya tienen el estado propuesta del modulo de rfq

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#193]
en el modulo de RFQS en _rfqs/admin_  ya no vale la pena que salgan las rfqs que estan en el estado "propuesta"    esas dejalas en el modulo de propuestas, si en el modulo de propuesta se le regresa el estado ... tons se veran en rfqs.....
me explique???  @ircsasw

**Comment by ircsasw** [comment]
@emacevedoc claro.

**Comment by RoyArgaez** [comment]
Esto se puede verificar.

**Comment by emacevedoc** [comment]
Ok  nada mas quitar del drop list dónde se filtra 

Enviado desde mi iPhone
