### ISSUE TITLE
error TE. no lo esta jalando correctamente el reporte propuesta

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#194]
Como puedes ver aqui puso TE = 250... y en el reporte sale 1  .... 

en la rfq externa..    10057518
fijate en los detalles yluego imprime el reporte de propuesta

**Comment by RoyArgaez** [comment]
Esto se puede verificar. Se tendría que crear una nueva propuesta ya que al momento de validar es cuando se graba en la BD el valor mayor.

**Comment by emacevedoc** [comment]
esto se cambio con @ircsasw, ya que el tiempo de entrega se modifico y se puso como de captura por cada item o partida, y ahora va a ser lo que se capture por cada partida, ya que cada una tendra su tiempo de entrega . y se jalara al reporte.

**Comment by RoyArgaez** [comment]
Esto se puede verificar.
