### ISSUE TITLE
permitir activar solicitudes de cotizaciones ya inactivadas

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#195]
En el modulo de administrar asi como se activas RFQs que ya se habian inactivado, permitir activar Solicitudes de cotizacion que ya se hayan inactivado.

**Comment by ircsasw** [comment]
Agregar la opción en el menú y hacer el proceso.
![image](https://cloud.githubusercontent.com/assets/919978/6489165/408b4bd0-c26a-11e4-8cf5-e4c79c77eb35.png)

**Comment by RoyArgaez** [comment]
Esto ya lo puede verificar.
