### ISSUE TITLE
partidas de rfqs inactivas no deben de seguir apareciendo para crear solicitudes

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#196]
al crear solicitudes de cotización nuevas... y me muestra los items no atendidos... salen items de rfqs que ya inactive ayer.. !!

![error](https://cloud.githubusercontent.com/assets/7875576/6489528/a0a332ae-c264-11e4-8a60-a609d0db249e.jpg)

**Comment by ircsasw** [comment]
@emacevedoc 

Esas partidas son de una RFQ que está activa, pero no se ve en el rfqs/admin por que tiene estado 5 (Propuesta), esa RFQ ya tiene una propuesta.
En rfqs/admin se ven 14 RFQs pero hay 33 RFQs activas: 14 con estado 1, 2, 3 o 4 (las que se pueden ver), 13 con estado 5 (Propuestas) y 6 con estado 9 (Declinadas).

Entonces, ¿esos items de esas RFQs si pueden ser solicitados de nuevo?

**Comment by emacevedoc** [comment]
si puedes porfa cambiale el edo a declinadas a todos los items q esten como "no atendidos" o inactivalos para q no me sigan aPARECIENDO como faltantes x cotizar y angel solo vea los de las rfqs vigentes

**Comment by emacevedoc** [comment]
ok lo voy a cerra... ya si veo algo raro abro otro issue.. gracias.
