### ISSUE TITLE
agregar el boton "editar" en clientes/view

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#198]
el mismo boton que esta en el admin que te lleve a  clientes/update con el id del cliente que estabas ya viendo en el view

**Comment by emacevedoc** [comment]
de hecho creo que asi deberia de ser en todos los view.. de todos los catalagos.. si entras a ver el detalle... de ahí deberias poder entrar a editar o corregir el que ya estas viendo.. 
ya que si vez un error tienes que volver a donde admnistrar.. volver a hubicar en la pagina en la que este el que quieres modificar y seleccionar editar y es un choro cuando son un buen.. en cambio si ya lo ubicaste y estas viendo el detalle y de ahi tambien le puedes dar al boton de editar te ahorras mucho tiempo .

**Comment by RoyArgaez** [comment]
Esto se puede verificar.

**Comment by emacevedoc** [comment]
lo pusiste en el catalogo de clientes...  yo lo pedí en el de contactos de los clientes.. pero esta bien tambien como te dije.. debiera de ser en todos y cada uno de los catálogos.. :)

**Comment by ircsasw** [comment]
No, no es necesario; Lo vamos a hacer para todos los catálogos, cerramos este cuando lo tengan todos los catálogos.

**Comment by RoyArgaez** [comment]
Esto lo puede verificar, ya está en todos los catálogos a excepción de **TiposCambio**

**Comment by emacevedoc** [comment]
http://sps.marineprov.com/index.php?r=proveedores/admin

1.- el de proveedores marca error.
![image](https://cloud.githubusercontent.com/assets/7875576/6547058/e0a88ce8-c591-11e4-90ea-cdaddfb4dc91.png)

**Comment by emacevedoc** [comment]
2.- el de monedas te manda al de editar usuarios en vez de editar la moneda
![image](https://cloud.githubusercontent.com/assets/7875576/6547063/2fa037d8-c592-11e4-84c3-d8c27a39d367.png)

![image](https://cloud.githubusercontent.com/assets/7875576/6547062/2b06ea8c-c592-11e4-86e7-d8b7a09f6bf3.png)

**Comment by RoyArgaez** [comment]
Ya corregí el error. Lo puede verificar.
