### ISSUE TITLE
no aparece el correo del vendedor en el reporte de propuesta

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#199]
en el reporte impreso de la propuesta no jala el email del vendedor, si aparece en el detalle pero no en la versión impresa...  ! :)

**Comment by RoyArgaez** [comment]
Se puede verificar

**Comment by emacevedoc** [comment]
no sale el email... sale en telefono !!!

**Comment by RoyArgaez** [comment]
Acabo de hacer una prueba, sale el email, eso lo había corregido ya. Puede verificar nuevamente.

**Comment by emacevedoc** [comment]
ahora si ya sale..  gracias.
