### ISSUE TITLE
campo more_info para cada Item

### ISSUE THREAD

**Issue by RoyArgaez** [lauraeg/incidencias_sps#201]
- [x] Eliminar botón **rfqs/admin**
- [x] agregar campo en items
- [x] agregar checkbox dentro del multimodel en **rfqs/update**
- [x] **if** *items.more_info = 1* **then** *rfqs.more_info = 1*

**Comment by ircsasw** [comment]
No se te olvide:
- [ ] Quitar código obsoleto 
- [ ] Quitar campos obsoletos

**Comment by RoyArgaez** [comment]
@emacevedoc Esto se puede verificar.

**Comment by emacevedoc** [comment]
funcionno bien en el update... pero creo que se borraron los datos de fechas... puedes verificar si tiene algo que cver con la modificación? mira la rfq 10058128 en administrar aparece sin los datos de las fechas.. mira.
![image](https://cloud.githubusercontent.com/assets/7875576/6546958/77c99810-c58d-11e4-8063-30edb1b1d34a.png)

**Comment by emacevedoc** [comment]
lo del more info en el update funcionó muy bien ;)  solo es ver lo de las fechas q se borraron.

**Comment by RoyArgaez** [comment]
Puede probar de nuevo? hice varias pruebas y a mi no me elimina las fechas al editar la RFQ

**Comment by emacevedoc** [comment]
ya no me salio a mi... pero si te fijas algo para que se borran esas fechas... quizá no es este lo que lo que lo provoca. voy a cerrar este issue.. ahí si sale de nuevo te aviso.. :) @ircsasw

**Comment by RoyArgaez** [comment]
Tal vez al crear la RFQ por el error que le marcó, no guardó las fechas, pero eso está corregido, estoy pendiente si le marca error de nuevo.
