### ISSUE TITLE
erorr en propuesta impresa en el Total en letras NO cuadra con la moneda seleccionada

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#202]
en el monto en letras.. pone   MN..     y no debe... debe de poner la moneda que escogi para la propuesta...  por ejemplo esta propuesta escogimos hacerla en dolares.. USD  pero en la descripcion en letras del monto... viene en MN !!

![image](https://cloud.githubusercontent.com/assets/7875576/6546969/d9fde950-c58d-11e4-9a93-aa5d6dc147e2.png)

**Comment by emacevedoc** [comment]
un detallito.. dolares.. lleva acento...  dólares.

**Comment by lauraeg** [comment]
Lo bueno es que eso está de tu catálogo de monedas. ;)

**Comment by emacevedoc** [comment]
nop..... en la descripción en letras de la cantidad no viene de mi catalogo..
la descripcion en letras dice xxx dolares 38/100 U$   entiendo que la parte final si esta en mi catalogo pero no la palabra dolares....

**Comment by lauraeg** [comment]
ahm.. lo checo

**Comment by RoyArgaez** [comment]
Sí está en su catálogo de monedas, es el nombre que le da a las monedas en plural.

![captura de pantalla de 2015-03-10 17 10 50](https://cloud.githubusercontent.com/assets/4944467/6586609/c525e9ee-c748-11e4-9fa1-c5f624fa0a8b.png)

**Comment by emacevedoc** [comment]
AH OK ES Q ESTABA VIENDO EL CATALGO DE TIPOS D CAMBIO . JEJEJ GRAXS.
PREGUNTA ES POSIBLE Q SE PONGA EN MAYÚSCULAS EL MONTO EN LETRAS??

**Comment by RoyArgaez** [comment]
Lo puede verificar.

**Comment by emacevedoc** [comment]
gracias. !
