### ISSUE TITLE
no permite asignar en el cuadro comp cuando solo es una sola partida.

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#203]
si unicamente hay un item.. en el cuadro comparativo, y quiero asignarle a el la cantidad a colocar... como tengo que cambiar el foco, no guarda el valor tecleado.
PORQUE NO MEJOR SE LE PONE UN BOTON DE GUARDADO. ??
si no ,,, favor de corregir como se guarda el campo si no me deja cambiar de foco y x lo tanto no guarda el dato.

**Comment by RoyArgaez** [comment]
@emacevedoc  Al colocar una cantidad en el campo, presione el botón _Enter_ para guarda automáticamente el valor.

**Comment by emacevedoc** [comment]
ok.
