### ISSUE TITLE
AGREGAR COLUMNA EN GRID propuestas/admin

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#205]
AGREGAR EL MONTO TOTAL DE LA PROPUESTA JUNTO A LA COLUMNA DE MONEDA..

DE MANERA QUE VEAS MONTO.. Y LUEGO MONEDA.

**Comment by RoyArgaez** [comment]
Se puede verificar

**Comment by emacevedoc** [comment]
Alienado a la derecha porfA 

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Listo
