### ISSUE TITLE
CORREGIR LA DESCRIPCION EN LETRAS DE LA PROPUESTA IMPRESA propuestas/reppropuesta

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#206]
EJEMPLO EN LA COTIZACION O PROPUESTA 38 VERSION 2

CUARENTA Y NUEVE MIL DOSCIENTOS DIECISIETE
PESOS M/N 56/100 $

EJEMPLO.. SI TE FIJAS.. DICE PRIMERO   PESOS m/n  56/100  
DEBE DECIR..    PESOS  56/100    m/n  
EL M/N   VA DESPUÉS DE LOS CENTAVOS.. NO ANTES.
Y EL SIMBOLO  $$   YA NO DEBE DE SALIR EN EL IMPORTE EN LETRAS

**Comment by RoyArgaez** [comment]
Esto lo puede verificar.
