### ISSUE TITLE
AJUSTAR COLUMNAS DEL REPORTE IMPRESO propuestas/reppropuesta

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#207]
ACHIQUITAR MAS LA COLUMNA DE ITEM, 
JUNTAR MAS LAS COLUMNAS DE UNIDAD Y DE TE..  YA QUE SALEN MUY JUNTOS LAS COLUMNAS DONDE VAN LAS CANTIDADES  DE PRECIO UNITARIO E IMPORTE.

LO MISMO PARA DONDE ESTAN LOS TOTALES...  EL SIMBOLO SE SEPARA DE LA CANTIDAD PORQUE NO ENTRA LA CANTIDAD..

**Comment by RoyArgaez** [comment]
Puede verificar si así está correcto.
