### ISSUE TITLE
MARCO ESTE ERROR AL FILTRAR UNA RFQ 

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#208]
ME SALE ESTA VENTANA AL ESCRIBIR UN RFQ EXTERNO EN EL GRID PARA FIRLTRALO.
ERROR 500

**Comment by RoyArgaez** [comment]
¿Cuál es el RFQ que le marca ese error?

**Comment by emacevedoc** [comment]
propuestas/ventaporclie&id=69   ya que filtre las de protexa...   quiero filtrar en el grid por el campo rfq externo, ya que son vairas d ese cliente y al ponerle 23724  y cambiarme de lugar.. sale una ventana con el error.. solo me marca al filtrar en ese campo.

**Comment by RoyArgaez** [comment]
Esto ya lo puede verificar.
