### ISSUE TITLE
SOLO DEBE MOSTRAR LAS PARTIDAS DE PROPUESTAS VALIDAS NO DE LAS DECLINADAS

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#209]
OJO AL HACER LAS ORDENES DE COMPRA ESTAMOS HABLANDO QUE SOLO PUEDO SELECCIONAR ITEMS DE LAS ULTIMAS VERSIONES DE PROPUESTA O SNAPSHOTS...  RECUERDA QUE AQUI SE DEBEN VER UNICAMENTE LAS VERSIONES FINALES.

SI HAY UNA CERO Y HAY UNA UNO... SOLO DEBO VER LOS ITEMS DE LA UNO... NO DE LA CERO.

SI SOLO HAY VERSION CERO.. PUES SOLO LA CERO..
SI HAY CERO, UNO DOS Y TRES.. DEBO VER UNICAMENTE DE LA TRES...

**Comment by RoyArgaez** [comment]
Esta parte ya está.

**Comment by emacevedoc** [comment]
nop... no esta.. porque al filtrar primero las de protexa....  al irme a la pantall propuestas/ventaporclie para seleecionar las partidas de la rfq externa 23724.. salen partidas repetidas de una misma rfq externa.. xq hay dos propuestas de dicha rfq..   la 0 y la 1.. 
y de hecho una de ellas esta declinada..

no estoy hablando de la rfq.. estoy hablando que la propuesta este declinada. !

**Comment by emacevedoc** [comment]
ojo.. en el grid propuestas/admin... si se deben ver todas las propuestas con todas las versiones y sus estados..   pero en el momento de mostrar los items para hacer la orden de compra... solo deben ir los items de las propuestas de las ultimas versiones  y no canceladas, para efectos de crear la orden de compra.
esto es... el grid administro y controlo las propuestas.. pero en el de los items q se muestran es nada mas para ir creando la orden de compra que me coloco el cliente. y no puede colocarme de versiones viejas.. tiene q ser de la mas vigente.

**Comment by emacevedoc** [comment]
oyep...   esta ya lo analizamos mejor :))   siempre si se van a poder repetir.. pero entonces agrégale las columas de propuesta  y version junto a la de rfq externo.

unicamente no deben estar la de las propuestas declinadas. !

**Comment by RoyArgaez** [comment]
La columna de propuesta se está refiriendo al folio ?

**Comment by emacevedoc** [comment]
si creo q si es el numero de la propuesta.
