### ISSUE TITLE
visualizar las condiciones de la prop del proveedor en el momento de editar precio x partida al cliente.

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#210]
Los campos que ya se capturan en solicitudes/update en la parte de abajo:
1.- Condiciones de envío
2.- Condiciones de pago
3.- Lugar de entrega
4.- Notas

deben poder verse en la ventana de editar precios que se abre dede rfqs/armapropuesta por cada partida abajo del campo otros notas, los 3 campos
pero bloqueado solo para lectura.

ojo son condiciones generales a nivel  de solicitud de cotizacion..  pero para efectos de armar el precio de un item  deben poder verse por item segun el seleecionado para editar.. si tienes duda llamame.

**Comment by ircsasw** [comment]
![image](https://cloud.githubusercontent.com/assets/919978/7141044/9c9b7de2-e294-11e4-8803-d97ae46aaa8c.png)

**Comment by RoyArgaez** [comment]
Las partidas en la respuesta del proveedor tienen condiciones individuales, ¿cuáles se mostrarán en el modal al editar precio, las individuales, las globales o ambas?

![captura de pantalla de 2015-04-14 20 09 23](https://cloud.githubusercontent.com/assets/4944467/7150606/bcdbd702-e2e2-11e4-8ff7-ed2438f0c385.png)

**Comment by emacevedoc** [comment]
ambas

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
No veo lugar de entrega ni notas.. Ni los botones de cancelar o guardar

**Comment by RoyArgaez** [comment]
Lo puede verificar, los botones están en la parte de abajo de las "condiciones por partida"

**Comment by emacevedoc** [comment]
Ok tal vez x q lo toy viendo en la tablet ...

**Comment by emacevedoc** [comment]
por favor cambiale el titulo a la seecion.. q se llame condiciones del proveedor

**Comment by RoyArgaez** [comment]
Esto se puede verificar

**Comment by emacevedoc** [comment]
Ya quedo. Sólo t comento q en la iPad no se ve completa la ventana...pero levanto otro issue para eso ese no urge.
