### ISSUE TITLE
una vez seleecionadas las partidas de la orden de compra falta continuar

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#213]
poner un botón abajo para cambiar de ventana.. ya que seleccione todas las partidas darle un botón de continuar para dos cosas:

uno poner los datos de la orden de compra...

Núm. de orden de compra:
version:
fecha de colocación:
Cliente: (este no cambia)
Nombre de quien compra : (este puede ser diferente d quien me envió la requisición)
autoriza:
archivos de la orden de compra:

**Comment by RoyArgaez** [comment]
@emacevedoc este issue es igual al #179 ?

**Comment by RoyArgaez** [comment]
Estos son los campos que estamos proponiendo en la tabla de *Ordenes* 
id
folio
revision
fecha_alta
id_cliente
contacto
recibe
autoriza
acepta_parciales
penaliza
importe
descuento
subtotal
impuestos
total
fecha_entrega
notas
--
Y estos son los de la tabla *Ordenado*
--

id
id_orden
estado
item
descripcion
cantidad
cantidad_ordenada
unidad
precio_unitario
importe
descuento
importe_desc
exento
tasa_iva
tasa_ieps

Esos campos están bien? o cuáles son los que debe llevar?

**Comment by emacevedoc** [comment]
Si .. estan bien…

 

De: Roysel Argaez [mailto:notifications@github.com] 
Enviado el: miércoles, 22 de abril de 2015 14:21
Para: lauraeg/incidencias_sps
CC: emacevedoc
Asunto: Re: [incidencias_sps] una vez seleecionadas las partidas de la orden de compra falta continuar (#213)

 

Estos son los campos que estamos proponiendo en la tabla de Ordenes 
id
folio
revision
fecha_alta
id_cliente
contacto
recibe
autoriza
acepta_parciales
penaliza
importe
descuento
subtotal
impuestos
total
fecha_entrega


notas


Y estos son los de la tabla Ordenado 


id
id_orden
estado
item
descripcion
cantidad
cantidad_ordenada
unidad
precio_unitario
importe
descuento
importe_desc
exento
tasa_iva
tasa_ieps

Esos campos están bien? o cuáles son los que debe llevar?

**Comment by RoyArgaez** [comment]
@emacevedoc 
Los campos "*contacto, recibe, autoriza*" de la tabla **Ordenes**, con qué campos están relacionados en la BD?

**Comment by emacevedoc** [comment]
Contacto y recibe son id de contactos d clientes. Y recibe es d la tabla d usuarios de marine
