### ISSUE TITLE
al inactivar RFq´s de clientes en rfqs/admin declinar partidas en sol de cotizaciones

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#215]
hay que correr un scrip que haga lo siguiente:

1.-  busque los items de esas fqs enviados a mis proveedores en solicitudes de cotizacion.. y ponerles el estado en el item de la solicitud de cotizacion como declinado... y en notas se guardara "la rfq ha sido inactivada"  y se le sumara la misma justificación que el de ventas al declinar la rfq grabe.
ojo !! no se delicnara la solicitud de cotizacion... únicamente al item q pertenezca a esa rfq y este en esa solicitud.

obviamente si en una solicutd de cotizacion que tiene 4 partidas y las cuatro estan declinadas individuales el estado de la solicud será "declinado"

OJO... cuando la RFQ se active de nuevo desde el modulo de administracion _rfqs/reactivar_  hay que correr el mismo scrip pero al revez... debe poner los items como no atendidos si no tiene precio guardado o como atentido si tiene precio guardardo..

esta complicado... me explique???  te marque pero me dice q esta cortado :(

**Comment by RoyArgaez** [comment]
Este lo puede verificar.

**Comment by emacevedoc** [comment]
inactive una rfq.. y la solicitud de cotizacion relacionada si se puso su partida como declinada.. pero porque la solicitud no se ve como declinada.. si todas las partidas d esa solicitud estan declinadas ??

**Comment by ircsasw** [comment]
Se hace un stored procedure para realizar estas operaciones, es importante hacer pruebas y estar pendientes de su funcionamiento.
