### ISSUE TITLE
Xq en una ventana la prop está en mxn y en otra consulta en dólares .?..y no suma lo mismo

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#216]
En propuestas/admin. La propuesta de folio 36 tiene un total de 61,998.27 mxn
Y en   La suma de los dos ítems  da.   61,998.26.     Y además en usd

**Comment by RoyArgaez** [comment]
¿En dónde lo ve en DLS?

**Comment by emacevedoc** [comment]
propuestas/ventaporfol&id=42&folio=36&revision=0
y en propuestas/ventaporclie&id=69

**Comment by ircsasw** [comment]
@RoyArgaez 
Al utilizar el tipo de cambio de $14.9862 se están acarreando decimales, hay que hacer todas las operaciones con redondeo a dos decimales.
Cuando se define la moneda y se guarda el tipo de cambio en lo propuesto, se hacen las operaciones para definir los importes de la propuesta, estas operaciones se deben hacer con cantidades redondeadas a dos decimales.

**Comment by RoyArgaez** [comment]
Si mostramos las cantidades con todos sus decimales, la operación es correcta, no se puede sumar directamente la columna de *importe_total* de los **PROPUESTOS** y compararlos con el *total* de la **PROPUESTA** sin tomar en cuenta todos los decimales.

*importe_total* de propuestos sirve para evaluar individualmente cada propuesta.

Si vemos los importes con todos los decimales las operaciones cuadran.

![captura de pantalla de 2015-04-28 19 37 26](https://cloud.githubusercontent.com/assets/4944467/7383074/50867b78-edde-11e4-8093-07733dc3a218.png)

**Comment by emacevedoc** [comment]
en todas las cuentas utiliza solo dos dígitos por favor...
