### ISSUE TITLE
no funciona el filtro de revision. en propuestas/ventaspor

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#217]
le pongo una version..2 y no la encuenta.. le pongo version 0 y tampoco por lo que creo q este filtro no esta funiconando correctamente porque si hay propuestas de versiones 0,1,2,3
perdon revision.

**Comment by RoyArgaez** [comment]
¿Cómo?, jeje no entendí, disculpe.

**Comment by emacevedoc** [comment]
En propuestas/ventaspor entiendo q hay cuatro filtros
X NUM d propuesta, folio, rfq externa y cliente..?

**Comment by RoyArgaez** [comment]
No, los filtros son 3 "*Cotización o folio y revisión*", "*rfq externo*" y "*clientes*"

En los primero se escribe el folio y la revisión de la propuesta y únicamente muestra los items de esa propuesta.
En el filtro de "*rfq externo*" al igual que en el de "*clientes*" hace un filtrado de todos los items de todas las propuestas creadas con ese **rfq_externo** o **cliente**

No sé si me expliqué.

**Comment by emacevedoc** [comment]
Ok pensé q era x revisión también y al buscar sólo x ahi versiones traería .. X eso me marcaba error
