### ISSUE TITLE
hay un error de monedas en orden de compra o propuestas.. no ubico donde pero no salen iguales

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#220]
por ejemplo.. si veo desde propuestas la 23724   (propuestas/admin)   ahi se ve la moneda de esta en pesos...
y si la veo al colocar la orden de compra.. las partidas correspondientes a esa misma orden en armar la orden de compra...(propuestas/ventaporclie&id=69)  sale en dolares..!

**Comment by ircsasw** [comment]
Lo tenemos que platicar, la idea original es que de entrada en la vista de propuestas todo esté en la moneda principal; pero no se si te estoy entendiendo bien.

**Comment by emacevedoc** [comment]
esto ya quedo,.. se va a ver en la moneda que se propuso..
