### ISSUE TITLE
falta que se vaya a la ventana de administrar ordenes de compra...

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#222]
despues de crear la orden de compra.... el boton que dice administrar me lleva a ordenes/admin  falta ver ahi como se van a ver las ordenes de clientes ya hechas para darles seguimiento.

**Comment by RoyArgaez** [comment]
El botón **administrar** en la vista de ordenes la redirecciona en _ordenes/admin_

**Comment by emacevedoc** [comment]
ok...
