### ISSUE TITLE
falta ventana donde se tipea o se guardan los demas datos de la orden de compra.. y las cantidades colocadas

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#223]
una vez señaladas las partidas  en propuestas/ventaporclie  al darle continuar hay que editar los datos faltantes de la orden.. y las canitdades colocadas....    me manda a la de view... pero antes d la de view falta editarla.

**Comment by ircsasw** [comment]
Si, claro, así es, pero aun no lo tenemos, en eso estamos.

**Comment by RoyArgaez** [comment]
Faltan algunos detalles, pero ya se redirecciona para _update_
