### ISSUE TITLE
cambiar el menu de ordenes de compra

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#225]
el menu.. vENTAS -> Ordenes de compra al darle clic al menu te debe de llevar a ordenes/admin
y mostrarte las ordenes de compra que ya tienes .. si no tienes pues no t muestra ninguna.. pero t debe llevar al grid de ordenes primero con su correspondiente menu de admnistración..
en el menu de arriba de la misma ventana de ordenes/admin debe existir el boton de nueva +  y 
al darle a ese botón entonces te debe de llevar a la pantalla  propuestas/ventaspor   que es donde comienza a hacerse una nueva orden.
#222

**Comment by emacevedoc** [comment]
ME MARCA ERROR 403

**Comment by RoyArgaez** [comment]
Deberá recargar su navegador, debe ser el caché almacenado.

**Comment by emacevedoc** [comment]
ya cerre y volvi a abrir... ya apague y volvi a prender mi maquina. y nada..
