### ISSUE TITLE
correcciones en  ordenes/update

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#227]
* poner en color gris todos los campos No editables.
Cantidad	Unidad	Precio Unitario	Descuento	Importe Desc	Tasa Iva	Tasa Ieps	Exento

*el campo "autoriza" es un campo d captura.. y es dato de la orden d compra del cliente. no es de marine ni de la rfq. debe de ir en blanco para que se capture.

*"recibe" es un campo que se selecciona del personal de marine es diferente de quien captura la orden tambien. deben ser dos campos.el otro campo de quien captura la orden no se debe de ver.. es interno. pero debe guardarse quien capturo la orden.

*"fecha de entrega" debe ser <= "fecha alta"

*el campo "cantidad ordenada" debe llevar nada mas dos decimales. no cuatro. y debe validarse numerico ya que escribi letras y continuo al darle guardar... debío decirme que no era numero y no dejar continuar.

*el campo "orden externa"  debe decir "# orden externa" y debe ser obligatorio y no lleno por default como esta ahorita.

*incluir el campo TE propuesto x partida en las partidas y el campo notas

**Comment by RoyArgaez** [comment]
@emacevedoc
- El campo _notas_ es un campo editable? o viene de las partidas?
- El campo _recibe_ debe ser un campo editable?

**Comment by RoyArgaez** [comment]
@emacevedoc
- El campo _notas_ es un campo editable? o viene de las partidas?
- El campo _recibe_ será editable igual? 
- El campo _captura_ con qué campo está relacionado en la tabla **propuestas**?

**Comment by emacevedoc** [comment]
Notas a nivel partida viene d propuestas.
El notas abajo es a nivel orden d compra editable
El campo recibe es editable pero dl catálogo de usuarios d marine 
Y el campo captura no es editable es quien captura la orden en el sistema 


Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Faltan estos últimos detalles que me acaba de mencionar, lo demás lo puede verificar.

**Comment by emacevedoc** [comment]
OK.. OYE..
CANTIDAD A ORDENAR POR PARTIDA NO ME DEJA PONER DECIMALES.. Y SI PUEDE LLEVAR DECIMALES  (2) Y EL MENSAJE DE EROR ME DICE QUE TIENE QUE SER ENTERO ESTO ES FALSO.. PORQUE A VECES ME COLOCAN COSAS QUE USAN DECIMALES..  134.45 METROS POR EJEMPLO.

**Comment by emacevedoc** [comment]
Y LOS CAMPOS SI LOS VEO PERO NO SE LES VE EL TITULO DEL CAMPO ARRIBA.. UNICAMENTE EL CAMPO.

**Comment by RoyArgaez** [comment]
Ya está, puede verificarlo

**Comment by emacevedoc** [comment]
al entrar a una que ya habia yo puesto la cantidad ordenada  no se reflejan los datos de totales.. hasta que no vuelvo a cambiar de foco dentro de las partidas.. si hay hay cantidad ordenada.. debe de actualizarse el dato de abajo...

**Comment by RoyArgaez** [comment]
Esto lo sigo revisando.

**Comment by RoyArgaez** [comment]
Esto lo puede verificar.

**Comment by emacevedoc** [comment]
los totales no me estan cuadrando..
ordenes/update&id=18   en esta orden al entrar me marca 10,501.80  pero nada que ver si multiplico las cantidades... colocadas con los precios .......

**Comment by RoyArgaez** [comment]
Estuve revisando de dónde provienen esas cantidades, en algún proceso de solicitudes no actualizó la cantidad de la partida. En la imagen de abajo se muestra la cantidad correcta al multiplicar la *cantidad_solicitada* x 2
![image](https://cloud.githubusercontent.com/assets/4944467/7547841/08470078-f5bb-11e4-84e7-2f832b77d9c2.png)
en algún proceso detuvo la actualización de los importes lo que hizo que se grabara con las cantidades como si la cantidad_solicitada sea 18 
![image](https://cloud.githubusercontent.com/assets/4944467/7547871/e88bbebc-f5bb-11e4-8237-d3cee1c16d56.png)

vamos a dar un recorrido al código para encontrar en dónde pudo ocurrir ese detalle que no pasa siempre.
