### ISSUE TITLE
campos a ver en el grid de administrar ordenes ordenes/admin

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#228]
"# orden compra" ,
Cliente,
Contacto,
Recibe, 
Fecha
Fecha alta
Fecha de entrega.
Total
Moneda
Estado

**Comment by emacevedoc** [comment]
no me deja verlo.. me sale error 403 el menu.. de hecho no me deja ver nada el menu.

**Comment by RoyArgaez** [comment]
El mismo error del caché. yo puedo acceder sin problemas

![captura de pantalla de 2015-05-05 07 41 44](https://cloud.githubusercontent.com/assets/4944467/7472648/3ad5d50a-f2fa-11e4-8e4a-0ab3182cc485.png)

**Comment by emacevedoc** [comment]
esta es mi pantalla.. ya le di f5..  ya abri y cerre navegador y ya reinicie.
![image](https://cloud.githubusercontent.com/assets/7875576/7474513/8ddd5392-f307-11e4-82f2-e5c4f85b5f77.png)

**Comment by RoyArgaez** [comment]
Puede probar de nuevo?

**Comment by emacevedoc** [comment]
Ahora sip

Enviado desde mi iPhone
