### ISSUE TITLE
ERROR 403 AL DARLE AL MENU.. VENTAS/ORDENES DE COMPRA

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#229]
ME MARCA ERROR NO ME DEJA VER LAS OTRAS VENTANAS.

**Comment by RoyArgaez** [comment]
¿Cómo? No entiendo el error. Estoy probando en la web

**Comment by emacevedoc** [comment]
no me deja revisar avances porque no paso de ahi....
ayer xq habia dejado abierta la pagina de update.. pero hoy quiero entrar y no puedo pasar de ahi.. porque me sale esto.
![image](https://cloud.githubusercontent.com/assets/7875576/7474319/326139e4-f306-11e4-8f05-fa4498198667.png)
