### ISSUE TITLE
en ordenes/update alinear los campos de abajo a la derecha

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#230]
Donde se ven las cantidades totales alineadas a la derecha por favor. todas con dos decimales

Importe *	
Subtotal *	
Descuento *	
Impuestos *	
Total *

**Comment by emacevedoc** [comment]
encontre la liga en mi historial y ya pude revisar esto.. pero el error sigue apareciendome desde el menu no puedo entrar

**Comment by ircsasw** [comment]
@RoyArgaez este issue está cerrado y REVISADO pero tiene otro comentario.

@emacevedoc lo abro para que definas si todo está bien.

**Comment by emacevedoc** [comment]
si ya esta este.... gracias.
