### ISSUE TITLE
en ordenes/update las sig correcciones

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#235]
primera columna
cliente..  debe ser obligatorio..
contacto..  debe ser obligatorio..
autoriza...  no obligatorio.. pero debe ser del catalgo igual al de contacto de cliente.

2da columna.  
No orden ..   obligatorio
recibe...  obligatorio (que se vea igual q contacto con la lupa)

3er columna
fecha de la orden. obligatorio
fecha de entrega.. obligatorio
fecha de alta.. se debe llenar la primera vez q sea crea el registro automatico al grabar y no debe modificarse después

en el grid de partidas
exento debe ser gris
moneda debe ser la descripción no el id
debe haber un campo "importe" que se recalcule cuando cambie la cantidad ordenada dentro del grid con el resultado de multiplicar cantidad ordenada x precio unitario... sin iva.
.

**Comment by RoyArgaez** [comment]
1er Columna
- [x] cliente obligatorio
- [x] contacto obligatorio
- [x] autoriza obligatorio

2da columna
- [x] # Orden obligatorio
- [x] recibe obligatorio (faltan detalles)

3er Columa
- [x] fecha: obligatorio
- [x] fecha_entrega: obligatorio 
- [x] fecha_alta llena por default y deshabilitado para modificaciones.

Items
- [x] exento inhabilitado
- [ ] moneda
- [ ] campo importe

**Comment by emacevedoc** [comment]
es esta.. pero no lo veo hecho.. habia olvidado marcarla como del "orden de compra"

**Comment by emacevedoc** [comment]
veo que ya estan.. solo falta lo de moneda

**Comment by emacevedoc** [comment]
el campo autoriza.. no jala los contactos del cliente...  es el mismo catalogo de contactos de clientes..

**Comment by RoyArgaez** [comment]
Estoy revisando y SI, las mismas personas de contacto son las que salen en autoriza y en ambos casos están relacionas con el ID del cliente.
¿Cuál es el error?

**Comment by emacevedoc** [comment]
Q sale vacío al querer seleccionar uno 

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Puede verificarlo.
