### ISSUE TITLE
marca error al darle DETALLE

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#236]
CDbException
La tabla "orden_files" definida en la clase active record "OrdenFiles" no se ha podido encontrar en la base de datos. 

/home/marine/public_html/sps/framework/db/ar/CActiveRecord.php(2362)

2350 
2351     /**
2352      * Constructor.
2353      * @param CActiveRecord $model the model instance
2354      * @throws CDbException if specified table for active record class cannot be found in the database
2355      */
2356     public function __construct($model)
2357     {
2358         $this->_modelClassName=get_class($model);
2359 
2360         $tableName=$model->tableName();
2361         if(($table=$model->getDbConnection()->getSchema()->getTable($tableName))===null)
2362             throw new CDbException(Yii::t('yii','The table "{table}" for active record class "{class}" cannot be found in the database.',
2363                 array('{class}'=>$this->_modelClassName,'{table}'=>$tableName)));
2364         if($table->primaryKey===null)
2365         {
2366             $table->primaryKey=$model->primaryKey();
2367             if(is_string($table->primaryKey) && isset($table->columns[$table->primaryKey]))

**Comment by emacevedoc** [comment]
al darle detalle e ir a ordenes/view

**Comment by RoyArgaez** [comment]
listo
