### ISSUE TITLE
la moneda debe ser obligatoria de seleccionar antes de ver el grid del cuadro comparativo

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#240]
solicitudes/comparaporrfq    
te muestra el grid abajo y con las variaciones de monedas.. hay modo de forzar que primero escoja una moneda antes de ver el grid abajo, alguna propiedad de visible o invisible..????

**Comment by RoyArgaez** [comment]
Sigo verificando la lista.

**Comment by emacevedoc** [comment]
la lista no sale en usd ni mnx.. y la de folio 513,, tiene dolares y pesos.. y solo me deja escoger pesos..

**Comment by RoyArgaez** [comment]
Puede verificarlo, aún continuo verificando las otras modificaciones relacionadas.

**Comment by emacevedoc** [comment]
si ya salen las monedas disponibles. pero aun no t forza a escoger primero la moneda antes de hacer visible el grid...

**Comment by RoyArgaez** [comment]
Puede verificarlo
