### ISSUE TITLE
debe funcionar como el cuadro comparativo por rfq. lo del comparar por moneda

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#241]
solicitudes/comparaporsol no tiene lo del unificar moneda como el cuadro comparativo por rfq solicitudes/comparaporrfq 

y este se debe funcionar como el  #240

**Comment by RoyArgaez** [comment]
Lo puede verificar. Ya quedó.

**Comment by emacevedoc** [comment]
en solicitudes/comparaporsol   sale sin nada en el list.  donde selecino la moneda a comprar

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
EN solicitudes/comparaporsol SOLO ME SALE LA MONEDA MXN...  Y DEBE DE SALIR CON TODAS LAS MONEDAS EN LAS QUE SE HAYAN COTIZADO LAS PARTIDAS DE LAS SOLCIITUDES.
POR EJEMPLO ESTA..
solicitudes/comparaporsol&id=2541&folioagrupa=513
TIENE PARTIDAS EN MXN Y EN USD... EL LIST ME DEBE PERMITIR ESCOGER EN QUE LO QUIERO COMPARAR... SI PESOS O DOLARES.

**Comment by RoyArgaez** [comment]
Sigo verificando la lista de las monedas.

cerraré este issue, y mantendré el  issue #240 que está relacionado

**Comment by emacevedoc** [comment]
le dare revisar cuando ambos esten listos.. :)
