### ISSUE TITLE
cambiar el estado de propuestas agregando un estado. cuando guarde la orden de compra

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#242]
cuando una orden de compra se captura en el modulo de ordenes de compra,,, si me colocan una partida x  ..  en la propuesta de que fue tomada debe de cambiar el estatus de la propuesta a "Asignada", aunque solo sea una partida...  si son mas de una no importa, el estado estará ahora como asignada.

**Comment by emacevedoc** [comment]
esto sin importar q la propuesta estará como creada o como enviada.

**Comment by RoyArgaez** [comment]
@emacevedoc  Igual a los items de la propuesta se les pondrá el estado **asignada**?

**Comment by emacevedoc** [comment]
Solo a los ítems asignados los otros no cambian de estado 

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Lo puede verificar.
