### ISSUE TITLE
ORDENAR POR FOLIO, VERSION POR DEFAULD propuestas/admin

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#244]
SIEMPRE Q SE CARGUE LA PRIMERA VEZ QUE SEA ORDENADO POR   (FOLIO, VERSION)  D MENOS A MAYOR.

**Comment by RoyArgaez** [comment]
Se puede verificar

**Comment by emacevedoc** [comment]
si pero volviste a cambiarle el nomre a la columan de revision.. no es revision es "version"

**Comment by emacevedoc** [comment]
"Versión" lleva acento.

**Comment by emacevedoc** [comment]
Sigue apareciendo revisión en lugar de versión

**Comment by RoyArgaez** [comment]
Ya se corrigió la etiqueta de "VERSIÓN" y se ordena de menor a mayor.

**Comment by emacevedoc** [comment]
no se esta ordenenado correctamente si te fijas en la ventana dos de _propuestas/admin_ aparece el folio /version:
86	0	
39	3	
87	0	
88    1
89    0
88    2

**Comment by RoyArgaez** [comment]
Esto lo puede verificar

**Comment by emacevedoc** [comment]
sigue apareciendo en la venta dos de los registros, mal ordenados
84 0
85 0
70 1 <--
86 0
39 3  <--
87 0
88 0
88 1
89 0   <--
88 2
