### ISSUE TITLE
es posible fijar el foco en un campo para forzar la captura ?

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#245]
cuando rfqs/update   y pones en el campo estado "declinada" es posible que al cambiar de foco o que luego de seleccionar "declinada" te cambie al campo de notas de la misma partida en automatico para capturar el poque de la declinada???????

**Comment by RoyArgaez** [comment]
Puede verficar

**Comment by emacevedoc** [comment]
ya cheque y no pasa... onde lo pusiste o donde lo veo??? xq lo probe y nada..

**Comment by RoyArgaez** [comment]
Pues en *RFQS/UPDATE* donde lo pidió, al momento de seleccionar el estado **declinado** del item en el drop, el foco se le agrega al campo notas.

**Comment by emacevedoc** [comment]
Aparece abajo una liga q estas cediendo pero no hace nada 

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Lo puede verificar

**Comment by emacevedoc** [comment]
ya lo verifique.. se vuleve un desmadre.. xq cada q cambio algo en un campo editable y le doy tab me manda al primer campo de notas de la primera partida.. algo quedo chueco ahi.. solo debe mandar al campo notas de la partida que requiera que se le escriba un motivo de haberle puesto declinado siempre y cuando No tenga capturado nada. si no para que me regresa al campo y peor aun de un campo q notiene que ver con esa partida.

**Comment by RoyArgaez** [comment]
¿Cómo? Estoy verificando esta parte, edito algo de X partida y presiono TAB y no pasa eso, al seleccionar del dropdown el estado declinado, el foco aparece en notas de la partida que declino

**Comment by emacevedoc** [comment]
ok.. mira edita un item y cancelalo... di efectivamente te lleva a notas de dicha partida..
pero cambiate a una partida mas abajo y edita el campo descripcion... y al darle tab de ese campo me lleva al campo notas de la partida uno.

**Comment by RoyArgaez** [comment]
Lo estoy probando en la web, no me pasa lo que menciona, tal vez sea su caché que esté afectando esa parte, porque a mi no me da ese error.

**Comment by emacevedoc** [comment]
ya lo cheque en mi maquina no pasa.. en la de mi hermano pasaba pero ya se fue a comer.. deja regresa y lo termino de revisar.. gracais
