### ISSUE TITLE
se borraron los estados !! no se que paso!! en propuestas/admin de las asignadas

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#246]
Algo sucedio. con unas propuestas.. de las cuales ya habiamos hecho ordenes de compra y ya aparecia el estado de la Propuesta como "Asignada" ayer.. y hoy que entre.. aparecen sin estado, sin embargo las abro en detalle y el estado de la partida si se conservo.. algo paso y no ubico donde.

**Comment by RoyArgaez** [comment]
Lo verifico

**Comment by RoyArgaez** [comment]
Está corregido este error, lo puede verificar
