### ISSUE TITLE
agregar columna de Total dentro de las partidas.  en solicitudes/update

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#247]
agregar en el grid de partidas por cada partida un campo calculado y actulaizado cada que se capture un "precio cotizado" solicitudes/update que se llame "Total" antes del campo "moneda cotizada"
no me sirve que se guarde en la base. unicamente para visión en la pantalla es para detectar errores de captura al momento de registrar el precio.

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
alinearlo a la derecha.. son montos de moneda deben ir alienados a la derecha.
porque alguno si hay capturados precios... al cargar la pantalla me aparece en ceros.. y no hace el calculo al cargar ??

**Comment by RoyArgaez** [comment]
Listo
