### ISSUE TITLE
agregar la columan # orden externo en el ordenes/admin

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#248]
despues del # orden (de marine) agregar la columna "# orden externo"

**Comment by emacevedoc** [comment]
Me llama la atención si # de orden externa es obligatorio como permitió guardar dos órdenes de compra sin ese campo y aparecen vacío¿..

**Comment by RoyArgaez** [comment]
No permite guardar. Las validaciones se hacen correctas, pudo haber pasado que en vez de presionar guardar, presionaron cancelar, eso haría que no se modifique la información ya insertada al crear la orden.

**Comment by emacevedoc** [comment]
ya le capture d nuevo el num d orden exteerno por que si tenian y no puedieron ir en blanco pesto q son requeridas al crearlas !!
.. pero ya otro error.. el campo   recibe y contacto no son obligarotio y aunque tienen marcado con arsterisco no obliga a capturarlos y debe.

**Comment by RoyArgaez** [comment]
Lo verifico

**Comment by RoyArgaez** [comment]
Este issue está relacionado con el #253 ?

**Comment by emacevedoc** [comment]
la columna ya esta.. pero lo del campo "recibe y contacto dentro del update tienen que ser obligatorios tambien.. no deben ir vaciós

**Comment by RoyArgaez** [comment]
Puede verificar la validación.

**Comment by emacevedoc** [comment]
array(2) { ["contacto"]=> array(1) { [0]=> string(30) "Complete los campos requeridos" } ["recibe"]=> array(1) { [0]=> string(30) "Complete los campos requeridos" } } ordenes

luego de seleccionar los items.. y darle continuar.. me salio esto...

**Comment by emacevedoc** [comment]
@ircsasw este marca error.

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
@ircsasw  arturo...esto sigue estando mal... tenemos q buscar como cambiarlo.. voy a cerrar este issue q fue el del aumento de la columna.. saludos.
