### ISSUE TITLE
error en solicitudes de cotización, no debe aparecer una partida si la rfq no esta vigente

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#249]
Al crear una solicitud de cotizacion nueva me sale la familia de “DESCONOCIDO”, eso significa que existe una RFQ vigente con esa familia no?

bueno al seleccionar unicamente esa familia me sale un item de un RFQ externo. (10047510A )

Resulta que al buscar ese mismo RFQ en requisiciones ( rfqs/admin )para que onda con esa requisición nos damos cuenta que en la lista de RFQ no aparece por lo que ya se inactivo, tons ya no debe de seguir saliendo para solicitar a cotizar.
 
Me fui a buscarla en activación para ver de pura chiripa estaba ahi y tampoco esta, tons el error son dos..
1.- no debe salir la partida para solicitar cotizaciones si ya no esta vigente
2.- sino esta en inactivas..... donde esta o porque sale????

**Comment by RoyArgaez** [comment]
Revisé la BD y encontré que la *RFQ* está activa, al crear una propuesta con X rfq, este cambia a estado **5. Propuesta** lo que hace que en el *rfqs/admin* no aparezca.

Crearemos un proceso que al inactivar todas las propuestas, el rfq regrese a su estado anterior para que vuelva a ser visible en *rfqs/admin*

Mientras regresaré la RFQ al estado **4. En validación** desde la BD

**Comment by emacevedoc** [comment]
No, si ya fue propuesta inactiva debe de estar dentro dl "modulo de administrar" como propuestas inactivas . 
Y en los ítems d las ya propuestas no deben seguirse solicitando a cotizar .

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Esto lo puede verificar, el módulo está creado.

**Comment by emacevedoc** [comment]
roy pero el titulo esta mal dice requisiciones inactivas debe decir propuestas inactivas y el campo revisión es "Versión"

**Comment by RoyArgaez** [comment]
Ya corregí los errores, qué filtros no le funcionan?

**Comment by emacevedoc** [comment]
referencia... no filtra correctamente,
 vendedor me marca error 500 cuando escribo algo a filtrar y me salgo del campo, 
fehca, vigencia, total, y moneda no filtran

**Comment by RoyArgaez** [comment]
Los puede verificar, ya revisé todos los filtros y me funcionan correctamente, acabo de subir los últimos cambios

**Comment by emacevedoc** [comment]
referencia, fecha y vigencia no funcionan bien
usd marca error 500

**Comment by RoyArgaez** [comment]
El filtro de Fecha y vigencia funcionan correctamente, la de moneda no me marca ningún error 
el formato de búsqueda de fecha y vigencia es como aparece 2014-11-12

**Comment by emacevedoc** [comment]
si pongo 2014 ... no debe jalar @RoyArgaez  ????

**Comment by RoyArgaez** [comment]
Si solo escribe el año, el día o la fecha, le filtra todas las propuestas que tengan esa fecha

**Comment by emacevedoc** [comment]
noup cuando pongo 2014 no me hace nada :(

**Comment by RoyArgaez** [comment]
Entonces borre su caché que debe estar afectando, porque yo lo pruebo en la web y en mi local y me funcionan correctamente

**Comment by emacevedoc** [comment]
la de usd si se corrigio pero la de fechas... si pongo 2014... me trae mal los registros.. me trae del 2015 tambien

**Comment by RoyArgaez** [comment]
Okey, lo verifico.

**Comment by RoyArgaez** [comment]
Lo puede verificar

**Comment by emacevedoc** [comment]
ya quedo fechas... falta referencia.

**Comment by RoyArgaez** [comment]
Lo estoy probando en la web y en mi local, me funciona correctamente en los dos.
Verifique de nuevo por favor.
