### ISSUE TITLE
Agregar Subtotal delante de total q no lleve iva like #247

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#250]
Agregar el campo antes del total pero sin iva, igual solo se calcule en pantalla

**Comment by RoyArgaez** [comment]
Puede verificarlo

**Comment by emacevedoc** [comment]
alinearlo a la derecha.. son montos de moneda deben ir alienados a la derecha.
porque alguno si hay capturados precios... al cargar la pantalla me aparece en ceros.. y no hace el calculo al cargar ??

**Comment by RoyArgaez** [comment]
Puede verificarlo.
