### ISSUE TITLE
el campo # orden externa debe de ser unico por cliente. _ordenes/update_

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#251]
puedo tener dos ordenes externas que sean el numero 100... pero de diferentes clientes... (me explico?
puedo tener la 100 de un cliente 1 y la 100 de un cliente b... pero no dos 100 de un solo cliente no debe permitirlo.

**Comment by RoyArgaez** [comment]
Esto lo puede verificar.
