### ISSUE TITLE
se borran los campos de fechas de la rfq cuando se hace el marcado de falta de informacion!!

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#252]
entra a ver las que hay acaban de marcar o solicitar mas informacion en unas partidas de una rfq q ya se habia guardardo previamente y en el _rfqs/admin_ ahora aparece en rojo pero sin fechas !!  se borraron..

**Comment by emacevedoc** [comment]
fecha rfq, fecha alta y fecha limite :(

**Comment by RoyArgaez** [comment]
Sabe qué fechas tenía esa RFQ?
Estoy haciendo las pruebas para producir ese error

![captura de pantalla de 2015-05-20 12 48 40](https://cloud.githubusercontent.com/assets/4944467/7732627/d6b8be24-feee-11e4-8079-ed310e4fa8fd.png)

son los que acabo de solicitar información, y no me borró ninguna fecha.

**Comment by emacevedoc** [comment]
nop... :(   dejame las busco.

**Comment by RoyArgaez** [comment]
Seguí con las pruebas, no me falló de nuevo. 
¿Usted podría hacer otra prueba para corroborar si pasa de nuevo?

**Comment by emacevedoc** [comment]
ok..si pasa lo reviso...y lo doy d alta again.
