### ISSUE TITLE
debe haber un rollback al crear orden de compra nuevas si no concluyo completo

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#253]
cuando estoy creando una orden de compra... como es en varios pasos...
1.-el primer paso seleeciono que partidas de las que ya propuse van a formar parte de la orden de compra que me colocaron.
2.- el segundo paso voy a adicionar los campos obligatorios (cliente, contacto, nuum de ordne y complementarios en la pagina ordenes/update.   si ahi le doy cancelar...  DEBE BORRARSE la orden de compra si no se guarda en blanco el  contacto , recibe y nume de orden externa..   y eso esta mal. o en todo caso debe de hacer una pagina que sea la de ordenes /create  y otra el update.

**Comment by RoyArgaez** [comment]
Puede verificarlo

**Comment by emacevedoc** [comment]
le pusiste un boton d cancelar.. pero si no le doy al boton.. y no concluyo aun asi se forma basura..
