### ISSUE TITLE
en las propuestas el valor del iva en el reporte impreso esta mal.

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#255]
la propuesta 102 por ejemplo.. el iva sale de 30%  y debe ser 16
y la propuesta 89 y la 90 igual...

**Comment by RoyArgaez** [comment]
Puede verificar las cantidades!!

**Comment by emacevedoc** [comment]
No jala bien la propuesta 102 sigue mal el calculo

**Comment by RoyArgaez** [comment]
La cantidad solicitada (100) se multiplica por 4050 que es el precio unitario, eso es correcto?

**Comment by emacevedoc** [comment]
por ejemplo mira.. en la 
http://www.sps.marineprov.com/index.php?r=propuestas/view&id=118

si ves el detalle.. ves que dice   161,147.51   como total...
subtotal tieen  82,992.32 y de impuestos dice 78155.19  !!!

**Comment by RoyArgaez** [comment]
Puede verificarlo nuevamente!

**Comment by emacevedoc** [comment]
sigue estando mal en el view y en el impreso.. no cuadra el iva...

**Comment by emacevedoc** [comment]
no se si el iva se guarda cuando se genera o se recalcula en el reporte... ??

**Comment by RoyArgaez** [comment]
En el reporte no se calcula nada, solo imprime lo que está en la BD. el iva está a 16%

**Comment by RoyArgaez** [comment]
Podría crear de nuevo la propuesta con folio 103 para verificar.
