### ISSUE TITLE
Guardarle la fecha a la requisicion 3754-90152

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#259]
no me deja ponerle las fechas q se borraron en algún punto que no hemos identificado cuando le pusieron q faltaba información.
xq ese campo se guarda en automatico cuando se crea..
puedes ponerlas en la base de datos directa? para que no este en blanco y le demos seguimiento correcto a la requisición porfa.

fecha alta : 19 /mayo/2015
fecha recibe: 19/mayo/2015
fecha rfq 19 /mayo/2015
fecha limite: 30/mayo/2015

**Comment by RoyArgaez** [comment]
Puede verificarlo
