### ISSUE TITLE
En el cuerpo del correo donde se envía la propuesta debe de ir lo sig.

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#260]
Estimado cliente, agradeciendo la oportunidad de cotizar y esperando vernos favorecidos con su pedido adjunto a este correo encontrará nuestra Propuesta correspondiente a su solicitud _campo referencia_.
Atentamente.

***
Dear customer, thanks for oportunity to quote, find attached our proposal for your request _campo referencia_.
Best Regards.

**Comment by emacevedoc** [comment]
ojo... el campo referencia... es el campo de la RFQ externa  que aparece como primer columa en propuestas/admin

**Comment by RoyArgaez** [comment]
Si, esto lo puede verificar

**Comment by emacevedoc** [comment]
en la parte en ingles... falta poner el campo refrerencia..

Hay modo que las referencias vayan en negritas ???

**Comment by RoyArgaez** [comment]
Lo verifico.

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
Estimado cliente, agradeciendo la oportunidad de cotizar y esperando vernos favorecidos con su pedido adjunto a este correo encontrará nuestra Propuesta correspondiente a su solicitud _campo referencia_.
Favor acusar de recibido.

Atentamente.

Dear customer, thanks for oportunity to quote, find attached our proposal for your request _campo referencia_.
Please acknowledge.
Best Regards.

**Comment by emacevedoc** [comment]
oye me pidieron hacer un cambio plis   0=)

**Comment by emacevedoc** [comment]
gracias.
