### ISSUE TITLE
Correcciones en el Email donde se envia la propuesta

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#262]
1.-El titulo del PDF.. Propuesta_SIGLAS_#Cot_#versión
donde las SIGLAS... son del vendedor que dice la propuesta. no de quien envía la propuesta
y #Cot  es el numero de propuesta o cotización
y #versión  es la versión.
actualmente sale el ID de la propuesta en el nombre.... y no debe ser el ID....

2.-El titulo del correo donde se envía la propuesta debe ser "Referencia: #RFQexterna  "
3.- el correo de donde se envía es el usuario capturado en el campo recibe #265 en la rfq. y mandara copia oculta a ese mismo usuario.

**Comment by emacevedoc** [comment]
verifica porfa la firma del correo.. debe ser el mismo que el usuario q recibe .. ya que esta cruzado.. aparece firmado en el cuerpo del correo por el que le dio al boton de enviar...

**Comment by emacevedoc** [comment]
verifica porfa la firma del correo.. debe ser el mismo que el usuario q recibe .. ya que esta cruzado.. aparece firmado en el cuerpo del correo por el que le dio al boton de enviar...

**Comment by RoyArgaez** [comment]
Lo puede verificar.
