### ISSUE TITLE
Correcciones en el Email donde se envia la solicitud de cotización

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#264]
like issue  #262 

1.-El titulo del PDF.. RFQ_SIGLAS_#solicitud
donde las SIGLAS... son del comprador de marine quien hizo la solicitud. no de quien envía la solicitud.
y #solicitud es el numero de solicitud de cotización

2.-El titulo del correo donde se envía la solicitud de cotización debe ser "Favor de cotizar RFQ_SIGLAS_#solicitud"

es que detectamos de que si otro le da enviar se hace un cruzado entre el titulo y el nombre del archivo y no coinciden.

**Comment by RoyArgaez** [comment]
@emacevedoc 
En este caso el comprador de la solicitud, es el campo "Solicita" de la tabla *solicitudes*?

**Comment by emacevedoc** [comment]
sip..

**Comment by RoyArgaez** [comment]
Puede verificarse.
