### ISSUE TITLE
agregar campos "captura" y "actualiza" y modificar "recibe"

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#265]
"captura" aquí se va a guardar el usuario quien cree la solicud en el sistema es decir en el _rfqs/create_ va a permitir guardarse con el usuario que esta capturando la RFQ la primera vez..
pero en el rfqs/update va a estar bloqueado solo mostrando quien fue el usuario que creo la RFQ previamente.
"actualiza"  va a ser quien esta creando y se actualiza de acuerdo al usuraio quien este modificando el rfqs/update

"recibe" va a ser seleccionable del catalogo de los usuarios del sistema en el _rfqs/create_ pero en el rfqs/update no se va a poder modificar.

**Comment by RoyArgaez** [comment]
Los 3 campos serán visibles en create y update?

**Comment by emacevedoc** [comment]
captura y actualiza no tienen que ser visibles ahi.. sino en el view..
captura y actualiza se grabaran en el create con el mismo usuario
pero actualiza es el unico que se modificara en el update.

recibe visibre en create y update... ..

**Comment by RoyArgaez** [comment]
Entendido.

**Comment by emacevedoc** [comment]
en rfqs/create   el campo recibe.. debe ser editable y seleccionado del catalogo de usuarios (sps) del sistema

**Comment by emacevedoc** [comment]
y captura y actualiza no se guardaron.. porque cree una rfq .. y en el view sale vacios los campos.

**Comment by RoyArgaez** [comment]
Listo, puede verificarlo.

**Comment by emacevedoc** [comment]
el campo recibe.. sigue sin ser editable y seleecionable del catalgo

**Comment by RoyArgaez** [comment]
Me podría mostrar una impresión de pantalla? por que en mi local el campo **recibe** en *UPDATE* no se puede editar y en el *CREATE* es un dropdown que sale de los usuarios del sistema.

**Comment by emacevedoc** [comment]
asi esta en mi create

![image](https://cloud.githubusercontent.com/assets/7875576/7876065/56d41106-058b-11e5-8af2-23460295669a.png)

**Comment by RoyArgaez** [comment]
Lo puede verificar.

**Comment by emacevedoc** [comment]
oye fe de erratas... el campo Recibe... en el update si debe poder cambiarse...

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
no se ve el campo..
![image](https://cloud.githubusercontent.com/assets/7875576/8062212/2414a2c8-0e94-11e5-8021-e53bc522d57e.png)

**Comment by RoyArgaez** [comment]
Lo estoy verificando en la web...

![captura de pantalla de 2015-06-09 10 45 11](https://cloud.githubusercontent.com/assets/4944467/8062338/c2bc21b2-0e94-11e5-9934-09550d44e190.png)

**Comment by emacevedoc** [comment]
no se ve ni en el create ahora.. :/

**Comment by RoyArgaez** [comment]
Puede verificarlo.

**Comment by emacevedoc** [comment]
Buenas tardes a ver estos datos asi están funcionando.

"Captura" se guarda en automatico en el create, es el usuario quien crea la RFQ en el sistema. una sola vez y no se modifica en el update. este campo o se debe de ver en la pantalla debe ser interno

"Actualiza" va a ser quien esta editando el Update...   no va a ser   este campo tampoco se debe ver en pantalla es interno.

"Recibe" va a ser Editable y Seleccionable del catalogo de TODOS los usuarios del sistema. por TODOS los usuarios.  este campo si debe verse y editable en pantalla.

**Comment by RoyArgaez** [comment]
El campo "Recibe" va a poder ser editable para cualquiera?

**Comment by emacevedoc** [comment]
Jajaja no déjalo como ya lo hicieron pa q se eduquen :p no mas conque sea requerido al guardar la primera vez . Pa q no marque error al update 

Enviado desde mi iPhone

**Comment by RoyArgaez** [comment]
Entonces ya quedó!! solo ud. puede modificar ese campo
