### ISSUE TITLE
erro en RFQ al guardado de rfq en las fechas

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#268]
no he platicado con la chica de ventas.. pero hay algo que esta mal y hace que se borren las fechas de la RFQ... 
ejemplo la rFQ externa TLO-46180 se capturo hoy y mira aparece sin fechas..

**Comment by RoyArgaez** [comment]
Lo estoy revisando...

**Comment by RoyArgaez** [comment]
Estuve verificando los procesos en RFQS, no me sucedió ese error, hay algún dato más que hayan ingresado, o algo que se haya hecho para que se genere ese error?

**Comment by emacevedoc** [comment]
no se ha presentado el error.. si se presenta abro otro issue.
