### ISSUE TITLE
NO ME DEJA HACER CUADRO COMPARATIVO DE LA RFQ EXTERNA PERFO-MEXI

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#269]
solicitudes/comparaporrfq&id=1198&rfqexterno=PERFO-MEXI
ME SALE EN BLANCO LA PAGINA... 
![image](https://cloud.githubusercontent.com/assets/7875576/7966257/870feffa-09e8-11e5-8be1-655f3b9f69cf.png)

**Comment by emacevedoc** [comment]
ya vi que es solo cuando haces el cuadro por rfq externo... supongo que es por lo de la moneda..  porque ahi no te muestra lo d la moneda como en el caso de por el cuadro por folio...  la busque por folio y si me dejo asignarlas.. pero por rfq sale en blanco..  supongo q ta invisible porque no se ha seleecionado la moneda pero tampoco sale donde elegirla.

**Comment by RoyArgaez** [comment]
Si le presiona en el botón de **Monedas** aparecerá el dropdown, pero enseguida lo pongo como visible.
