### ISSUE TITLE
Búsqueda rfqs/admin

### ISSUE THREAD

**Issue by lauraeg** [lauraeg/incidencias_sps#270]
En la ventana principal se puede realizar la búsqueda; ¿por qué razón hay que abrir otra vista con una relación de campos y que son los mismos que los del grid? :confounded:
![image](https://cloud.githubusercontent.com/assets/963627/8063575/13b2b472-0e9b-11e5-9153-576632575a7c.png)

**Comment by emacevedoc** [comment]
creo que esto es mas bien para el reporte de lista de las RFQs...
