### ISSUE TITLE
error en el estado de unos items en una propuesta..la 127

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#271]
creo que estan mal los estados de las partidas de lapropuesta..... mira en esta propuesta.. cuando entro al view.... aparecen partidas como asignadas y no estan asignadas !!

checate la cotizacion 127... hicimos una version en pesos y otra en dolares... y en el detalle de ambas aparece como asignadas algunos items..
![image](https://cloud.githubusercontent.com/assets/7875576/8134514/6dd5073c-10f5-11e5-92ee-19bbdf02f010.png)

**Comment by RoyArgaez** [comment]
Se le agregó asignado porque posiblemente crearon una Orden de compra con la propuesta! lo corregí en la BD, pero revisaré si me genera algún error! Por el momento lo cierro!!

**Comment by emacevedoc** [comment]
No se ha creado ninguna orden de compra respectiva a esta partida

**Comment by emacevedoc** [comment]
si se vuleve a presentar te digo... pero no hicimos ninguna orden con esas partidas..
