### ISSUE TITLE
No aparece ninguna moneda en esta ???

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#273]
http://www.sps.marineprov.com/index.php?r=rfqs/armapropuesta&id=1119.

pero le doy actualizar sin seleccionar nignua moneda y aparece en dolares !.. q pasión aquí ??

**Comment by RoyArgaez** [comment]
Lo reviso.

**Comment by RoyArgaez** [comment]
Estoy revisando este issue, y veo que las partidas que tiene esa RFQ, todas están declinadas, estoy revisando el filtro para saber porqué me muestra esas 3 que aparecen, pero sigo revisando.

**Comment by RoyArgaez** [comment]
Está corregido.

**Comment by emacevedoc** [comment]
probablemente las declinaron despues...

**Comment by emacevedoc** [comment]
pero lo corregiste o no las econtraste???
