### ISSUE TITLE
eliminar el campo de # orden de ordenes/admin

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#274]
ese dato no me sirve,

**Comment by emacevedoc** [comment]
te equivocaste de campo eliminaste # orden externa q es el que SI ME SIRVE Y DEBE SER OBLIGATORIO y REQUERIDO para que exista la orden de compra... el q no me sirve es el # orden

**Comment by RoyArgaez** [comment]
Mi error, una disculpa, este issue ya se puede verificar
