### ISSUE TITLE
la cant a colocar no puede ni debe ser mayor a la cantidad solicitada en la rfq

### ISSUE THREAD

**Issue by emacevedoc** [lauraeg/incidencias_sps#94]
la columna primera donde editas la cantidad a colocar por partida, No debe dejarme ponerle un numero mayo a la cantidad solicitada de esa partida en la RFQ del cliente.

**Comment by emacevedoc** [comment]
vamos a omitir el segundo punto ya que en el cuadro comparativo.. si puedo asignar de esta manera, es al momento de asignar para compra que no debe permitir comprar mas de lo de la orden de compra..   ok?

**Comment by RoyArgaez** [comment]
¿Eso es para el Update de ordenes?, ¿Y si al cliente se le hizo muy barato y quiere comprar más?
